#!/usr/bin/env python3
"""Keep the manual no-rebuild recovery workflow on the production release gates."""
from pathlib import Path
import argparse
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / '.github/workflows/neutral-edge-cutover.yml'
TARGET = ROOT / '.github/workflows/neutral-locale-resume.yml'


def generate(source: str) -> str:
    prepare, downstream = source.split('\n  shadow_review_hold:\n', 1)
    blocks = re.split(r'(?=^      - name: )', prepare, flags=re.M)[1:]
    steps = {block.splitlines()[0].removeprefix('      - name: '): block for block in blocks}
    header = '''# Generated by scripts/build_portal_locale_resume_workflow.py; shared gates are checked in tests.
name: Resume prepared multilingual release
run-name: Resume multilingual candidate from run ${{ inputs.source_run_id }} (no translation)

on:
  workflow_dispatch:
    inputs:
      source_run_id:
        description: "Completed source run with successful upload and static validation"
        required: true
        type: string
      source_run_attempt:
        description: "Exact source run attempt"
        default: "1"
        required: true
        type: string
      candidate_commit:
        description: "Source commit SHA of the uploaded candidate"
        required: true
        type: string
      candidate_slot:
        description: "Committed inactive slot"
        required: true
        type: choice
        options: [a, b]
      candidate_release:
        description: "Uploaded candidate release ID"
        required: true
        type: string
      candidate_tree:
        description: "Uploaded static tree SHA-256"
        required: true
        type: string
      previous_release:
        description: "Expected unchanged active release ID"
        required: true
        type: string
      previous_tree:
        description: "Expected unchanged active tree SHA-256"
        required: true
        type: string

permissions:
  contents: read
  actions: read

concurrency:
  group: portal-production-release
  cancel-in-progress: false

jobs:
  prepare_release:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
'''
    outputs = prepare.split('    outputs:\n', 1)[1].split('    steps:\n', 1)[0]
    outputs = outputs.replace('steps.runtime_context.outputs.static_release', 'steps.static_upload.outputs.static_release')
    outputs = outputs.replace('steps.operation.outputs.commit_sha', 'steps.static_upload.outputs.commit_sha')
    result = header + '    outputs:\n' + outputs + '    steps:\n'
    operation = steps['Require reviewed main operation']
    operation = operation.replace('${{ inputs.operation }}', 'migrate')
    operation = operation.replace('${{ vars.PORTAL_MULTILINGUAL_ENABLED || \'false\' }}', '"true"')
    # Every recovery is freshly reviewed, even if multilingual production was enabled meanwhile.
    operation = operation.replace('${{ vars.PORTAL_MULTILINGUAL_LIVE || \'false\' }}', '"false"')
    result += operation
    for name in ('Checkout public source', 'Set up Python'):
        result += steps[name]
    result += '''      - name: Install read-only recovery dependencies
        run: python3 -m pip install --disable-pip-version-check "boto3>=1.34,<2" "Pillow>=10.1,<12"

      - name: Validate recovery code and shared release gates
        run: |
          python3 -B scripts/build_portal_locale_resume_workflow.py --check
          python3 -B scripts/test_portal_locale_resume_workflow.py
          python3 -B scripts/test_resume_portal_locale_candidate.py
          python3 -B scripts/test_verify_prepared_static_slot.py
          python3 -B scripts/test_audit_portal_shadow_preview.py
          node --test workers/edge-static-host/test/index.test.mjs

'''
    for name in ('Prepare masked release context', 'Gate preparation on stable live routes',
                 'Capture exact previous state and public discovery'):
        result += steps[name]
    result += '''      - name: Restore verified uploaded candidate without rebuilding or translating
        id: static_upload
        env:
          GH_TOKEN: ${{ github.token }}
          SOURCE_RUN_ID: ${{ inputs.source_run_id }}
          SOURCE_RUN_ATTEMPT: ${{ inputs.source_run_attempt }}
          CANDIDATE_COMMIT: ${{ inputs.candidate_commit }}
          CANDIDATE_SLOT: ${{ inputs.candidate_slot }}
          CANDIDATE_RELEASE: ${{ inputs.candidate_release }}
          CANDIDATE_TREE: ${{ inputs.candidate_tree }}
          EXPECTED_PREVIOUS_RELEASE: ${{ inputs.previous_release }}
          EXPECTED_PREVIOUS_TREE: ${{ inputs.previous_tree }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
        run: |
          python3 -B scripts/resume_portal_locale_candidate.py \\
            --run-id "$SOURCE_RUN_ID" --run-attempt "$SOURCE_RUN_ATTEMPT" \\
            --expected-commit "$CANDIDATE_COMMIT" --expected-slot "$CANDIDATE_SLOT" \\
            --expected-release "$CANDIDATE_RELEASE" --expected-tree "$CANDIDATE_TREE" \\
            --expected-previous-release "$EXPECTED_PREVIOUS_RELEASE" --expected-previous-tree "$EXPECTED_PREVIOUS_TREE" \\
            --site-dir _neutral_site --diagnostics-dir "$RUNNER_TEMP/resume-diagnostics" \\
            --work-dir "$RUNNER_TEMP"

      - name: Confirm restored locale readiness
        id: locale_build
        run: echo 'ready=true' >> "$GITHUB_OUTPUT"

      - name: Retain exact Chinese parity report identity
        id: chinese_parity
        run: |
          python3 - <<'PY' >> "$GITHUB_OUTPUT"
          import hashlib, os
          from pathlib import Path
          print('sha256=' + hashlib.sha256(Path(os.environ['RUNNER_TEMP'], 'chinese-parity.json').read_bytes()).hexdigest())
          PY

      - name: Mark verified candidate as a pending release
        id: release_delta
        run: echo 'changed=true' >> "$GITHUB_OUTPUT"

'''
    names = ('Compute multilingual index policy identity',
             'Validate multilingual shadow sample plan before upload',
             'Prepare isolated multilingual shadow worker', 'Deploy isolated multilingual shadow worker',
             'Verify isolated multilingual shadow worker', 'Publish multilingual review identity',
             'Build public validation artifact', 'Upload release validation artifact')
    for name in names:
        if name == 'Upload release validation artifact':
            result += '''      - name: Preserve uploaded candidate provenance
        run: install -m 0600 "$RUNNER_TEMP/locale-resume-identity.json" _release_validation/candidate/locale-resume-identity.json

'''
        block = steps[name].replace('steps.operation.outputs.commit_sha', 'steps.static_upload.outputs.commit_sha')
        if name == 'Compute multilingual index policy identity':
            block = block.replace("${{ vars.PORTAL_MULTILINGUAL_INDEX_ALLOWLIST_PATH || '' }}", '""')
        result += block
    return result + '\n  shadow_review_hold:\n' + downstream


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    expected = generate(SOURCE.read_text())
    if args.check:
        if not TARGET.is_file() or TARGET.read_text() != expected:
            raise SystemExit('Recovery workflow must be regenerated from the current production gates')
        print('Recovery workflow retains exact production approval, cutover, acceptance and rollback gates')
    else:
        print('*** Begin Patch')
        if TARGET.exists():
            print(f'*** Update File: {TARGET}')
            print('@@')
            print(''.join('-' + line + '\n' for line in TARGET.read_text().splitlines()), end='')
        else:
            print(f'*** Add File: {TARGET}')
        print(''.join('+' + line + '\n' for line in expected.splitlines()), end='')
        print('*** End Patch')


if __name__ == '__main__':
    main()
