#!/usr/bin/env python3
"""Push KC translated Markdown reports into WeChat Official Account drafts.

The translated report workflow writes one folder per report under:

  kc_translated_reports/<date>/<report>/translated.md

This script converts those Markdown files into WeChat-compatible HTML, uploads
inline chart images through the article-image API, uploads one permanent image
material per article for the cover, creates draft items in chunks, and can
optionally submit those drafts for publishing.
"""
from __future__ import annotations

import argparse
import html
import json
import mimetypes
import os
import re
import struct
import sys
import time
import zlib
from pathlib import Path
from typing import Any
from urllib.parse import quote

import requests
from PIL import Image, ImageDraw

from institution_names import ensure_title_has_institution, infer_institution_name
from wechat_title_optimizer import (
    choose_best_wechat_title,
    clean_wechat_title as optimizer_clean_wechat_title,
    extract_wechat_keywords,
)
from sensitive_content_guard import sanitize_wechat_stock_language


BRAND = "KC桌面——外资精译"
AUTHOR = "KC桌面"
BOTTOM_DISCLAIMER = "For informational purposes only. Not investment advice."
DEFAULT_BODY_HOOK = (
    "更多完整报告、中文摘要、KC评论和图表合集，会放进每日国际信源汇编。"
    "适合快速扫当天主流叙事，也方便后续追问和横向比较。"
)
DEFAULT_BODY_VISIBLE_CHARS = 2000
DEFAULT_MIN_INLINE_IMAGES = 3
DEFAULT_ARTICLES_PER_DRAFT = 8
DEFAULT_MAX_CONTENT_CHARS = 19500
DEFAULT_MAX_CONTENT_BYTES = 18000
RAW_MARKDOWN_TITLE_MAX_CHARS = 96
DISPLAY_TITLE_MAX_CHARS = 35
WECHAT_AUTHOR_MAX_BYTES = 20
WECHAT_DIGEST_MAX_BYTES = 120
WECHAT_TITLE_MIN_CHARS = 20
WECHAT_TITLE_MAX_CHARS = 35
CONTENT_HEADER_TITLE_MAX_CHARS = 35
DEFAULT_WECHAT_IMAGE_UPLOAD_DELAY_SECONDS = 3.0
DEFAULT_WECHAT_ARTICLE_DELAY_SECONDS = 12.0
DEFAULT_WECHAT_DRAFT_DELAY_SECONDS = 90.0
DEFAULT_WECHAT_DRAFT_VERIFY_DELAY_SECONDS = 8.0
WECHAT_UPLOADIMG_MAX_BYTES = 1024 * 1024
WECHAT_UPLOADIMG_TARGET_BYTES = 930 * 1024
DEFAULT_TRAILING_IMAGE = "prompts/zsxq_img.jpg"
# Shown at the very end of every article, after the 星球 QR image.
DEFAULT_AFTER_IMAGE_NOTE = (
    "因公众号机制调整，可以关注并星标，更多查看此类内容"
)
POLLINATIONS_BASE_URL = "https://image.pollinations.ai/prompt/"
WECHAT_COVER_WIDTH = 1200
WECHAT_COVER_HEIGHT = 675
WECHAT_COVER_CROP_235_1 = "0_0.121693_1_0.878307"
WECHAT_COVER_CROP_1_1 = "0.21875_0_0.78125_1"
WECHAT_REQUEST_MAX_ATTEMPTS = 5
WECHAT_REQUEST_RETRY_BASE_SECONDS = 1.5
WECHAT_REQUEST_RETRY_MAX_SECONDS = 20.0
WECHAT_RETRYABLE_STATUS_CODES = {408, 425, 429, 500, 502, 503, 504}
WECHAT_RETRYABLE_ERRCODES = {-1}
WECHAT_TITLE_CHINA_RE = re.compile(
    r"(中国|大陆|内地|北京|人民币|A股|港股|\bChina\b|\bChinese\b|\bMainland\b|"
    r"\bBeijing\b|\bRMB\b|\bCNY\b|Hong Kong|\bHK\b|Taiwan)",
    re.I,
)
WECHAT_TITLE_CHINA_NEGATIVE_RE = re.compile(
    r"(负面|下行|放缓|收缩|疲弱|低迷|恶化|危机|风险|压力|冲击|衰退|萎缩|通缩|失业|"
    r"违约|债务|赤字|亏损|暴跌|崩盘|崩溃|泡沫|过剩|瓶颈|缺口|短缺|限制|封锁|"
    r"拖累|警告|担忧|不确定|不及预期|risk|slowdown|slump|weak|weakness|crisis|"
    r"recession|contraction|deflation|default|debt|deficit|loss|crash|collapse|"
    r"bubble|overcapacity|bottleneck|shortage|restriction|concern|uncertain)",
    re.I,
)
WECHAT_TITLE_CHINA_POLITICAL_RE = re.compile(
    r"(政治|政策|监管|管控|管制|供给侧|改革|政府|国务院|中央|官方|当局|审查|国安|"
    r"关税|贸易战|出口管制|资本管制|制裁|禁令|politic|policy|regulation|regulatory|"
    r"government|authority|official|censorship|tariff|trade war|export control|sanction|\bban\b)",
    re.I,
)
MID_ARTICLE_CTA_RE = re.compile(
    r"(扫码|社群|知识星球|星球|加微信|朋友圈|设为星标|设置星标|每日汇编|每天会把|"
    r"每天我会|国际信源汇编|完整报告与\s*KC评论|完整报告和\s*KC评论|更多国际信源|"
    r"喂给\s*AI|人工快速扫|市场\s*dynamics|图表合集|加入.*讨论|继续拆完整报告)",
    re.I,
)
MID_ARTICLE_CTA_CONTEXT_RE = re.compile(
    r"(单篇(?:文章|报告)|每天|每日|汇编|完整报告|KC评论|图表合集).{0,24}"
    r"(AI|汇编|社群|扫码|星球|图表合集|市场主线|横向比较|继续追问)",
    re.I,
)
INSTITUTION_KEY_TO_CN = {
    "imf": "IMF",
    "bis": "国际清算银行",
    "worldbank": "世界银行",
    "world bank": "世界银行",
    "oecd": "经合组织",
    "adb": "亚洲开发银行",
    "wef": "世界经济论坛",
    "unctad": "联合国贸发会议",
    "wto": "世界贸易组织",
    "bruegel": "布鲁盖尔研究所",
    "rand": "兰德公司",
    "brookings": "布鲁金斯学会",
    "mckinsey": "麦肯锡",
    "bcg": "波士顿咨询",
    "bain": "贝恩",
    "ark": "木头姐ARK",
    "ark invest": "木头姐ARK",
}
WECHAT_TITLE_STRONG_CHINA_SENSITIVE_RE = re.compile(
    r"(中共|共产党|党中央|政治局|习近平|反腐|国安法|台湾|台海|新疆|西藏|人权|民主|"
    r"抗议|示威|镇压|南海|军事|CCP|Communist Party|Xi Jinping|Taiwan|Taiwan Strait|"
    r"Xinjiang|Tibet|human rights|democracy|protest|crackdown|South China Sea|military)",
    re.I,
)
DATE_DIR_RE = re.compile(r"^\d{6,8}$")
IMAGE_TOKEN_RE = re.compile(r"\[\[KC_IMAGE_(\d{3})\]\]")
MD_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^\)]+)\)")
APPENDIX_RE = re.compile(
    r"^\s*#{1,6}\s*(?:附录|appendix|disclosure|disclaimer|important disclosures?|"
    r"analyst certification|重要披露|披露章节|披露|分析师认证|免责声明)\b",
    re.I,
)
TRAILING_DISCLOSURE_RE = re.compile(
    r"(?:仅供学习交流|不构成投资建议|deepseek|mineru|自动清洗|原报告作者|机构\s*logo|"
    r"translated by|generated by|"
    r"MS开展并寻求|MS\s+does and seeks|利益冲突|conflict of interest|"
    r"有关分析师认证|analyst certification|其他重要披露|important disclosures|"
    r"MS披露网站|MS Disclosure Website|投资代表|investment representative|"
    r"股价走势图|equity rating histories)",
    re.I,
)
USER_NOISE_LINE_RE = re.compile(
    r"^(?:MS亚洲有限公司\+?|MS ASIA LIMITED\+?|行业观点|Industry View|具吸引力|Attractive|"
    r"相关报告[:：].*|Related report:.*)$",
    re.I,
)
INSTITUTION_TITLE_ALIASES: list[tuple[str, list[str]]] = [
    ("高盛", ["GS", "Goldman Sachs"]),
    ("摩根大通", ["JPM", "J.P. Morgan", "JP Morgan", "JPMorgan"]),
    ("摩根士丹利", ["MS", "Morgan Stanley", "摩根斯坦利", "大摩"]),
    ("美银", ["BofA", "Bank of America", "美国银行", "美银证券"]),
    ("花旗", ["Citi", "Citigroup"]),
    ("瑞银", ["UBS"]),
    ("汇丰", ["HSBC"]),
    ("巴克莱", ["BARC", "Barclays"]),
    ("伯恩斯坦", ["Bernstein", "Sanford C. Bernstein", "Sanford Bernstein"]),
    ("杰富瑞", ["JEF", "Jefferies"]),
    ("德意志银行", ["DB", "Deutsche Bank", "德银"]),
    ("野村", ["NOM", "Nomura"]),
    ("美联储", ["Fed", "Federal Reserve"]),
]
TITLE_ALIAS_SEPARATOR_RE = r"(?:[：:，,、;；\-—]\s*)?"


class WeChatError(RuntimeError):
    def __init__(self, message: str, errcode: int | None = None, errmsg: str = "") -> None:
        super().__init__(message)
        self.errcode = errcode
        self.errmsg = errmsg


def log(message: str) -> None:
    print(message, flush=True)


def pacing_sleep(label: str, seconds: float, dry_run: bool = False) -> None:
    if dry_run or seconds <= 0:
        return
    log(f"{label}: pacing sleep {seconds:.1f}s")
    time.sleep(seconds)


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def regex_matches(pattern: re.Pattern[str], text: str) -> list[str]:
    matches: list[str] = []
    for match in pattern.finditer(text or ""):
        value = normalize_space(match.group(0))
        if value and value not in matches:
            matches.append(value)
    return matches


def wechat_title_policy_skip_reason(title: str) -> str:
    normalized = normalize_space(title)
    if not normalized:
        return ""

    strong_sensitive = regex_matches(WECHAT_TITLE_STRONG_CHINA_SENSITIVE_RE, normalized)
    if strong_sensitive:
        return "china_political_sensitive_terms=" + ",".join(strong_sensitive[:6])

    china_terms = regex_matches(WECHAT_TITLE_CHINA_RE, normalized)
    if not china_terms:
        return ""

    negative_terms = regex_matches(WECHAT_TITLE_CHINA_NEGATIVE_RE, normalized)
    if negative_terms:
        return (
            "china_negative_title_terms="
            + ",".join(china_terms[:4])
            + ";negative="
            + ",".join(negative_terms[:6])
        )

    political_terms = regex_matches(WECHAT_TITLE_CHINA_POLITICAL_RE, normalized)
    if political_terms:
        return (
            "china_political_policy_terms="
            + ",".join(china_terms[:4])
            + ";sensitive="
            + ",".join(political_terms[:6])
        )

    return ""


def canonicalize_institution_title_name(title: str) -> str:
    normalized = normalize_space(title)
    normalized = normalized.replace("摩根斯坦利", "摩根士丹利")
    normalized = normalized.replace("美国银行", "美银")
    return normalized


def alias_pattern(alias: str) -> str:
    if alias.lower() == "bofa":
        return r"(?<![A-Za-z])BofA(?=(?:Q[1-4]|\d|[^A-Za-z]|$))"
    if re.fullmatch(r"[A-Z]{2,5}", alias):
        return rf"(?<![A-Za-z]){re.escape(alias)}(?![A-Za-z])"
    if re.fullmatch(r"[A-Za-z. ]+", alias):
        return r"\b" + re.escape(alias).replace(r"\ ", r"[\s._-]+") + r"\b"
    return re.escape(alias)


def limit_title_colons(title: str) -> str:
    cleaned = normalize_space(title).replace(":", "：")
    if "：" not in cleaned:
        return cleaned
    head, tail = cleaned.split("：", 1)
    tail = re.sub(r"\s*：\s*", "，", tail).strip(" ，")
    if not tail:
        return head.strip()
    return f"{head.strip()}：{tail}"


def clean_leading_report_slug(title: str) -> str:
    cleaned = normalize_space(title)
    cleaned = re.sub(
        r"^([^：:]{1,18}[：:]\s*)(?:\d{4}[-_])?\d{1,4}[-_]\d{1,4}[-_]+",
        r"\1",
        cleaned,
    )
    cleaned = re.sub(r"^(?:\d{4}[-_])?\d{1,4}[-_]\d{1,4}[-_]+", "", cleaned)

    def readable_slug_tail(value: str) -> str:
        if value.count("-") + value.count("_") < 3:
            return value
        value = value.replace("_", " ")
        value = re.sub(r"\s*-{2,}\s*", "，", value)
        value = re.sub(r"\s*-\s*", " ", value)
        return normalize_space(value)

    for sep in ("：", ":"):
        if sep in cleaned:
            head, tail = cleaned.split(sep, 1)
            return f"{head.strip()}：{readable_slug_tail(tail.strip())}".strip("： ")
    return readable_slug_tail(cleaned).strip(" -_")


def remove_redundant_title_aliases(title: str) -> str:
    cleaned = clean_leading_report_slug(canonicalize_institution_title_name(title))
    for cn_name, aliases in INSTITUTION_TITLE_ALIASES:
        cleaned = re.sub(
            rf"^({re.escape(cn_name)})[：:]\s*{re.escape(cn_name)}\s*{TITLE_ALIAS_SEPARATOR_RE}",
            rf"\1：",
            cleaned,
            flags=re.I,
        )
        alias_group = "|".join(alias_pattern(alias) for alias in aliases)
        cleaned = re.sub(
            rf"^({re.escape(cn_name)})[：:]\s*(?:{alias_group})\s*{TITLE_ALIAS_SEPARATOR_RE}",
            rf"\1：",
            cleaned,
            flags=re.I,
        )
        cleaned = re.sub(
            rf"^(?:{alias_group})\s*[：:]\s*({re.escape(cn_name)})\s*{TITLE_ALIAS_SEPARATOR_RE}",
            rf"\1：",
            cleaned,
            flags=re.I,
        )
        cleaned = re.sub(
            rf"^({re.escape(cn_name)})\s*(?:\(|（)\s*(?:{alias_group})\s*(?:\)|）)\s*{TITLE_ALIAS_SEPARATOR_RE}",
            rf"\1：",
            cleaned,
            flags=re.I,
        )
    cleaned = re.sub(r"\s*[：:]\s*", "：", cleaned)
    cleaned = re.sub(r"：{2,}", "：", cleaned)
    return limit_title_colons(cleaned).strip("：: -—")


def strip_unexpected_leading_institution_prefix(title: str, institution_name: str) -> str:
    expected = canonicalize_institution_title_name(institution_name)
    cleaned = remove_redundant_title_aliases(title)
    for _ in range(3):
        for cn_name, aliases in INSTITUTION_TITLE_ALIASES:
            if canonicalize_institution_title_name(cn_name) == expected:
                continue
            prefix_group = "|".join([re.escape(cn_name), *(alias_pattern(alias) for alias in aliases)])
            replaced = re.sub(
                rf"^(?:{prefix_group})\s*[：:，,、;；\-—]\s*",
                "",
                cleaned,
                flags=re.I,
            ).strip()
            if replaced != cleaned:
                cleaned = replaced
                break
        else:
            break
    return cleaned


def draft_title_key(title: str) -> str:
    key = remove_redundant_title_aliases(title)
    key = re.sub(r"\s+", "", key)
    key = key.replace(":", "：")
    return key


def strip_title_institution_prefix(title: str) -> str:
    cleaned = remove_redundant_title_aliases(title)
    if "：" not in cleaned:
        return cleaned
    head, tail = cleaned.split("：", 1)
    if len(head) <= 12:
        return tail.strip(" ，,。；;：:")
    return cleaned


def title_fingerprint(title: str) -> str:
    cleaned = strip_markdown_markup(title)
    cleaned = remove_redundant_title_aliases(cleaned)
    cleaned = re.sub(r"^(?:标题|微信标题|公众号标题)\s*[：:]\s*", "", cleaned)
    cleaned = re.sub(r"[\s，,。；;：:、!！?？\-—“”\"'《》〈〉（）()【】\[\]]+", "", cleaned)
    return cleaned.lower()


def title_fingerprints(*titles: str) -> set[str]:
    keys: set[str] = set()
    for title in titles:
        for value in [title, strip_title_institution_prefix(title)]:
            key = title_fingerprint(value)
            if len(key) >= 8:
                keys.add(key)
    return keys


def text_is_duplicate_title(text: str, reference_titles: set[str]) -> bool:
    key = title_fingerprint(text)
    if len(key) < 8:
        return False
    for ref in reference_titles:
        overlap = min(len(key), len(ref))
        if overlap >= 10 and (key == ref or key in ref or ref in key):
            return True
    return False


def trim_title_complete(text: str, max_chars: int, min_chars: int = 0) -> str:
    cleaned = normalize_space(text).strip(" ，,。；;：:、-—")
    if len(cleaned) <= max_chars:
        return cleaned

    candidates: list[str] = []
    for match in re.finditer(r"[，,；;。！？!?]", cleaned):
        candidate = cleaned[: match.start()].strip(" ，,。；;：:、-—")
        if max(min_chars, 8) <= len(candidate) <= max_chars:
            candidates.append(candidate)
    if candidates:
        return candidates[-1]

    candidate = cleaned[:max_chars].strip(" ，,。；;：:、-—")
    candidate = re.sub(r"(?:以及|或者|因为|如果|但是|只是|而是|正在|成为|显示|指出|包括|对于|通过|需要|不是|还是|可以|已经|将|的|和|与|及|在|对|为|从|向|到|但|而)$", "", candidate)
    return candidate.strip(" ，,。；;：:、-—")


def trim_title_primary_clause(text: str, max_chars: int, min_chars: int = 0) -> str:
    cleaned = normalize_space(text).strip(" ，,。；;：:、-—")
    if len(cleaned) <= max_chars:
        return cleaned
    for match in re.finditer(r"[，,；;。！？!?]", cleaned):
        candidate = cleaned[: match.start()].strip(" ，,。；;：:、-—")
        if max(min_chars, 8) <= len(candidate) <= max_chars:
            return candidate
    return trim_title_complete(cleaned, max_chars, min_chars)


def remove_generic_title_noise(title: str) -> str:
    cleaned = normalize_space(title)
    candidate = re.sub(r"(?:[，,、]\s*)?公司情况更新(?:\s*[，,、])?", "，", cleaned)
    candidate = re.sub(r"\s*([：:，,、])\s*", r"\1", candidate)
    candidate = re.sub(r"[，,、]{2,}", "，", candidate)
    candidate = re.sub(r"：[,，、]+", "：", candidate).strip(" ，,、：:")
    if len(strip_title_institution_prefix(candidate)) >= 6:
        return candidate
    return cleaned


def fit_wechat_title(title: str, institution_name: str = "") -> str:
    cleaned = remove_redundant_title_aliases(title)
    cleaned = remove_generic_title_noise(cleaned)
    cleaned, _stock_changes = sanitize_wechat_stock_language(cleaned)
    cleaned = optimizer_clean_wechat_title(
        cleaned,
        institution_name,
        max_chars=max(RAW_MARKDOWN_TITLE_MAX_CHARS, WECHAT_TITLE_MAX_CHARS),
    )
    cleaned = remove_generic_title_noise(cleaned.replace("…", ""))
    cleaned = limit_title_colons(cleaned)
    if len(cleaned) <= WECHAT_TITLE_MAX_CHARS:
        return cleaned.strip("：: -—")

    prefix = ""
    tail = cleaned
    if "：" in cleaned:
        head, rest = cleaned.split("：", 1)
        if len(head) <= 12:
            prefix = f"{head}："
            tail = rest

    if prefix and len(prefix) < WECHAT_TITLE_MAX_CHARS - 8:
        tail_budget = WECHAT_TITLE_MAX_CHARS - len(prefix)
        fitted_tail = trim_title_primary_clause(tail, tail_budget, max(8, WECHAT_TITLE_MIN_CHARS - len(prefix)))
        if fitted_tail:
            return f"{prefix}{fitted_tail}".strip("：: -—")
    return trim_title_primary_clause(cleaned, WECHAT_TITLE_MAX_CHARS, WECHAT_TITLE_MIN_CHARS).strip("：: -—")


def content_header_title(raw_title: str, wechat_title: str) -> str:
    raw_clean = remove_redundant_title_aliases(raw_title).replace("…", "")
    body = strip_title_institution_prefix(raw_clean)
    outer_body = strip_title_institution_prefix(wechat_title)
    refs = title_fingerprints(wechat_title, outer_body)

    clauses = [
        item.strip(" ，,。；;：:、-—")
        for item in re.split(r"[，,；;。！？!?]+", body)
        if item.strip(" ，,。；;：:、-—")
    ]
    if len(clauses) >= 2:
        for start in range(1, len(clauses)):
            candidate = "，".join(clauses[start:])
            if 10 <= len(candidate) <= CONTENT_HEADER_TITLE_MAX_CHARS and not text_is_duplicate_title(candidate, refs):
                return candidate
            fitted = trim_title_complete(candidate, CONTENT_HEADER_TITLE_MAX_CHARS, 10)
            if 10 <= len(fitted) <= CONTENT_HEADER_TITLE_MAX_CHARS and not text_is_duplicate_title(fitted, refs):
                return fitted

    fitted_body = trim_title_complete(body, CONTENT_HEADER_TITLE_MAX_CHARS, 10)
    if fitted_body and not text_is_duplicate_title(fitted_body, refs):
        return fitted_body
    return trim_title_complete(strip_title_institution_prefix(wechat_title), CONTENT_HEADER_TITLE_MAX_CHARS, 8) or wechat_title


def sharpen_wechat_title(title: str, institution_name: str = "") -> str:
    cleaned = remove_redundant_title_aliases(strip_markdown_markup(title))
    cleaned = re.sub(r"^(?:标题|微信标题)\s*[：:]\s*", "", cleaned)
    cleaned = re.sub(r"真正的变量不是", "关键不是", cleaned)
    cleaned = re.sub(r"而是企业能否", "而是能否", cleaned)
    cleaned = re.sub(r"正在经历的不是", "不是", cleaned)
    cleaned = re.sub(r"真正的分水岭", "分水岭", cleaned)
    if institution_name:
        cleaned = strip_unexpected_leading_institution_prefix(cleaned, institution_name)
        cleaned = ensure_title_has_institution(cleaned, canonicalize_institution_title_name(institution_name))
    source_keywords = extract_wechat_keywords(cleaned, max_keywords=8)
    selected = choose_best_wechat_title(
        [cleaned, optimizer_clean_wechat_title(cleaned, institution_name, max_chars=WECHAT_TITLE_MAX_CHARS)],
        fallback=cleaned,
        institution_name=institution_name,
        source_keywords=source_keywords,
        max_chars=max(RAW_MARKDOWN_TITLE_MAX_CHARS, WECHAT_TITLE_MAX_CHARS),
    )
    return fit_wechat_title(selected, institution_name)


def truncate_chars(text: str, max_chars: int) -> str:
    text = normalize_space(text)
    if len(text) <= max_chars:
        return text
    return text[: max(0, max_chars - 1)].rstrip() + "…"


def truncate_utf8_bytes(text: str, max_bytes: int, suffix: str = "…") -> str:
    text = normalize_space(text)
    if len(text.encode("utf-8")) <= max_bytes:
        return text

    suffix_bytes = suffix.encode("utf-8")
    budget = max_bytes - len(suffix_bytes)
    if budget <= 0:
        return text.encode("utf-8")[:max_bytes].decode("utf-8", errors="ignore")

    kept: list[str] = []
    used = 0
    for char in text:
        size = len(char.encode("utf-8"))
        if used + size > budget:
            break
        kept.append(char)
        used += size
    return "".join(kept).rstrip() + suffix


def visible_char_count(text: str) -> int:
    return len(re.sub(r"\s+", "", strip_markdown_markup(text or "")))


def utf8_byte_count(text: str) -> int:
    return len((text or "").encode("utf-8"))


def truncate_visible_text(text: str, max_chars: int, suffix: str = "…") -> str:
    text = normalize_space(strip_markdown_markup(text))
    if max_chars <= 0 or visible_char_count(text) <= max_chars:
        return text
    budget = max(1, max_chars - visible_char_count(suffix))
    kept: list[str] = []
    used = 0
    for char in text:
        if char.isspace():
            kept.append(char)
            continue
        if used >= budget:
            break
        kept.append(char)
        used += 1
    candidate = normalize_space("".join(kept)).rstrip("，,。；;：:")
    for pattern in [r"[。！？!?；;]", r"[，,]"]:
        positions = [match.end() for match in re.finditer(pattern, candidate)]
        positions = [pos for pos in positions if pos >= min(36, max(18, budget // 2))]
        if positions:
            return candidate[: positions[-1]].strip()
    candidate = re.sub(r"(?:以及|或者|因为|如果|但是|只是|而是|正在|成为|显示|指出|包括|对于|通过|需要|不是|还是|可以|已经|将|的|和|与|及|在|对|为|从|向|到|但|而)$", "", candidate)
    return candidate.strip("，,。；;：:") + ("。" if candidate else "")


def latest_date_dir(root: Path) -> Path:
    if not root.exists():
        raise RuntimeError(f"Translated root not found: {root}")
    candidates = [p for p in root.iterdir() if p.is_dir() and DATE_DIR_RE.match(p.name)]
    if not candidates:
        raise RuntimeError(f"No date-named folders found under {root}")
    return max(candidates, key=lambda p: int(p.name))


def parse_selection_limit(value: str, label: str) -> int | None:
    normalized = str(value or "").strip().lower()
    if normalized in {"all", "*"}:
        return None
    try:
        limit = int(normalized)
    except ValueError as exc:
        raise ValueError(f"{label} must be a positive integer or 'all'") from exc
    if limit < 1:
        raise ValueError(f"{label} must be at least 1, or use 'all'")
    return limit


def parse_institution_filter(value: str) -> set[str]:
    filters: set[str] = set()
    for raw in (value or "").split(","):
        token = normalize_space(raw)
        if not token or token.lower() in {"all", "*"}:
            continue
        filters.add(INSTITUTION_KEY_TO_CN.get(token.lower(), token))
    return filters


def find_report_dirs(date_dir: Path) -> list[Path]:
    return sorted(
        [p for p in date_dir.iterdir() if p.is_dir() and (p / "translated.md").exists()],
        key=lambda p: p.name,
    )


def read_json(path: Path) -> dict[str, Any] | list[Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="ignore"))
    except Exception:
        return None


def clean_source_report_name(value: Any) -> str:
    raw = str(value or "").strip()
    if not raw:
        return ""
    name = Path(raw).name
    name = re.sub(r"\.pdf$", "", name, flags=re.I)
    name = re.sub(r"^\d{4}-", "", name)
    name, _stock_changes = sanitize_wechat_stock_language(name)
    name = re.sub(r"\s+", " ", name.replace("_", " ")).strip(" -._")
    return name[:240]


def source_report_name_from_xhs_dir(report_dir: Path) -> str:
    status = read_json(report_dir / "status.json")
    if isinstance(status, dict):
        cleaned = clean_source_report_name(status.get("source_pdf"))
        if cleaned:
            return cleaned
    return clean_source_report_name(report_dir.name)


def source_report_name_from_translated_dir(report_dir: Path, status: dict[str, Any] | list[Any] | None) -> str:
    if isinstance(status, dict):
        for key in ["source_report_original_name", "source_pdf", "original_report_name"]:
            cleaned = clean_source_report_name(status.get(key))
            if cleaned:
                return cleaned
        source_report_dir = status.get("source_report_dir")
        if source_report_dir:
            cleaned = source_report_name_from_xhs_dir(Path(str(source_report_dir)))
            if cleaned:
                return cleaned
    return clean_source_report_name(report_dir.name)


def strip_markdown_markup(text: str) -> str:
    text = re.sub(r"^\s*#{1,6}\s*", "", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = MD_IMAGE_RE.sub("", text)
    text = IMAGE_TOKEN_RE.sub("", text)
    return normalize_space(text)


def title_from_markdown(markdown: str, fallback: str) -> str:
    headings: list[str] = []
    for raw in markdown.splitlines():
        line = raw.strip()
        if line.startswith("#"):
            title = strip_markdown_markup(line)
            if title and not APPENDIX_RE.match(line):
                headings.append(title)
        if len(headings) >= 2:
            break
    if not headings:
        return truncate_chars(fallback, RAW_MARKDOWN_TITLE_MAX_CHARS)
    if len(headings) == 1:
        return truncate_chars(headings[0], RAW_MARKDOWN_TITLE_MAX_CHARS)
    combined = f"{headings[0]}：{headings[1]}"
    return truncate_chars(combined, RAW_MARKDOWN_TITLE_MAX_CHARS)


def digest_from_markdown(markdown: str) -> str:
    for raw in markdown.splitlines():
        line = strip_markdown_markup(raw)
        if len(line) >= 40 and not TRAILING_DISCLOSURE_RE.search(line):
            return truncate_utf8_bytes(line, WECHAT_DIGEST_MAX_BYTES)
    return ""


def clean_markdown(markdown: str) -> str:
    cleaned: list[str] = []
    in_code = False
    for raw in markdown.splitlines():
        line = raw.rstrip()
        if line.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        if APPENDIX_RE.match(line):
            break
        if USER_NOISE_LINE_RE.match(normalize_space(line)):
            continue
        if TRAILING_DISCLOSURE_RE.search(line):
            break
        cleaned.append(line)
    text, _stock_changes = sanitize_wechat_stock_language("\n".join(cleaned).strip())
    return text


def is_mid_article_cta_text(text: str) -> bool:
    cleaned = normalize_space(strip_markdown_markup(text))
    if not cleaned:
        return False
    return bool(MID_ARTICLE_CTA_RE.search(cleaned) or MID_ARTICLE_CTA_CONTEXT_RE.search(cleaned))


def strip_mid_article_cta_sentences(text: str) -> str:
    cleaned = normalize_space(text)
    if not is_mid_article_cta_text(cleaned):
        return cleaned
    sentences = re.findall(r"[^。！？!?；;]+[。！？!?；;]?", cleaned)
    kept = [
        sentence.strip()
        for sentence in sentences
        if sentence.strip() and not is_mid_article_cta_text(sentence)
    ]
    return normalize_space("".join(kept))


def highlight_terms_pattern(terms: list[str]) -> re.Pattern[str]:
    parts: list[str] = []
    for term in sorted(terms, key=len, reverse=True):
        escaped = re.escape(term).replace(r"\ ", r"\s+")
        if re.fullmatch(r"[A-Za-z0-9. &+-]+", term):
            parts.append(rf"(?<![A-Za-z]){escaped}(?![A-Za-z])")
        else:
            parts.append(escaped)
    return re.compile("|".join(parts), re.I)


HIGHLIGHT_BIG_NAME_RE = highlight_terms_pattern(
    [
        "Goldman Sachs",
        "Morgan Stanley",
        "J.P. Morgan",
        "JP Morgan",
        "JPMorgan",
        "Federal Reserve",
        "Bernstein",
        "高盛",
        "摩根大通",
        "摩根士丹利",
        "摩根斯坦利",
        "美联储",
        "伯恩斯坦",
        "美银",
        "花旗",
        "瑞银",
        "汇丰",
        "巴克莱",
        "德意志银行",
        "德银",
        "野村",
        "洪灏",
        "邢自强",
        "辜朝明",
        "特朗普",
        "马斯克",
        "Goldman",
        "JPM",
        "BofA",
        "Citi",
        "UBS",
        "HSBC",
        "Fed",
        "Trump",
        "Musk",
    ]
)
HIGHLIGHT_UPSIDE_RE = highlight_terms_pattern(
    [
        "强于预期",
        "高于预期",
        "超预期",
        "触底回升",
        "预期差",
        "上修",
        "改善",
        "回升",
        "复苏",
        "加速",
        "韧性",
        "拐点",
        "催化",
        "扩张",
        "降息",
        "宽松",
    ]
)
HIGHLIGHT_RISK_RE = highlight_terms_pattern(
    [
        "低于预期",
        "不及预期",
        "下行风险",
        "下修",
        "放缓",
        "承压",
        "压力",
        "风险",
        "疲软",
        "收缩",
        "亏损",
        "违约",
        "衰退",
        "通缩",
    ]
)
HIGHLIGHT_INSIGHT_RE = highlight_terms_pattern(
    [
        "KC评论",
        "换句话说",
        "这意味着",
        "核心是",
        "关键是",
        "重点是",
        "更重要的是",
        "注意",
        "一句话",
    ]
)
HIGHLIGHT_METRIC_RE = re.compile(
    r"(?<![A-Za-z0-9])(?:\d+(?:\.\d+)?\s*(?:%|pct|bp|bps|万亿|亿元|亿美元|亿|万|倍|x|X)|"
    r"20\d{2}年?|Q[1-4]|FY\d{2,4}|[一二三四五六七八九十]+季度)(?![A-Za-z0-9])",
    re.I,
)
HIGHLIGHT_RULES: list[tuple[str, re.Pattern[str], str]] = [
    ("insight", HIGHLIGHT_INSIGHT_RE, "color:#2F8F5B;font-weight:700;text-decoration:underline;"),
    ("big_name", HIGHLIGHT_BIG_NAME_RE, "color:#2457A7;font-weight:700;"),
    ("upside", HIGHLIGHT_UPSIDE_RE, "color:#2F8F5B;font-weight:700;"),
    ("risk", HIGHLIGHT_RISK_RE, "color:#B26B00;font-weight:700;text-decoration:underline;"),
    ("metric", HIGHLIGHT_METRIC_RE, "color:#2457A7;font-weight:700;text-decoration:underline;"),
]


def highlight_text_segment(segment: str, max_highlights: int) -> str:
    output: list[str] = []
    pos = 0
    count = 0
    while pos < len(segment):
        best: tuple[int, int, str, re.Match[str]] | None = None
        for _kind, pattern, style in HIGHLIGHT_RULES:
            match = pattern.search(segment, pos)
            if not match:
                continue
            candidate = (match.start(), -(match.end() - match.start()), style, match)
            if best is None or candidate[:2] < best[:2]:
                best = candidate
        if best is None or count >= max_highlights:
            output.append(segment[pos:])
            break
        _start, _length_key, style, match = best
        if match.start() > pos:
            output.append(segment[pos : match.start()])
        matched_text = match.group(0)
        output.append(f'<span style="{style}">{matched_text}</span>')
        pos = match.end()
        count += 1
    return "".join(output)


def apply_wechat_highlights(content: str, context: str = "body") -> str:
    if not content:
        return content
    max_highlights = 5 if context == "comment" else 7
    pieces = re.split(r"(<[^>]+>)", content)
    highlighted: list[str] = []
    in_code = False
    for piece in pieces:
        if not piece:
            continue
        if piece.startswith("<") and piece.endswith(">"):
            tag = piece.lower()
            if tag.startswith("<code"):
                in_code = True
            elif tag.startswith("</code"):
                in_code = False
            highlighted.append(piece)
            continue
        highlighted.append(piece if in_code else highlight_text_segment(piece, max_highlights))
    return "".join(highlighted)


def inline_markdown(text: str, context: str = "body") -> str:
    escaped = html.escape(text, quote=False)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    return apply_wechat_highlights(escaped, context)


def paragraph_html(text: str) -> str:
    content = inline_markdown(normalize_space(text))
    if not content:
        return ""
    if re.match(r"^(?:图|表)\s*\d+[\.:：\s]", content):
        return f'<p style="margin:18px 0 8px;color:#3f4a5a;font-weight:600;">{content}</p>'
    if content.startswith("来源：") or content.lower().startswith("source:"):
        return f'<p style="margin:4px 0 16px;color:#7a8494;font-size:13px;">{content}</p>'
    return f'<p style="margin:10px 0;line-height:1.78;color:#202631;font-size:16px;">{content}</p>'


def kc_comment_html(text: str) -> str:
    content = inline_markdown(normalize_space(text), context="comment")
    if not content:
        return ""
    return (
        '<section style="margin:18px 0;padding:13px 15px;background:#F1F8F4;'
        'border-left:4px solid #2F8F5B;color:#223044;font-size:15px;line-height:1.75;">'
        f"{content}"
        "</section>"
    )


def is_figure_meta_line(text: str) -> bool:
    content = normalize_space(strip_markdown_markup(text))
    return bool(re.match(r"^(?:图|表)\s*\d+[\.:：\s]", content)) or content.startswith("来源：") or content.lower().startswith("source:")


def heading_html(level: int, text: str) -> str:
    content = inline_markdown(strip_markdown_markup(text))
    if not content:
        return ""
    if level <= 1:
        return f'<h2 style="margin:24px 0 12px;color:#152033;font-size:22px;line-height:1.35;">{content}</h2>'
    return f'<h3 style="margin:22px 0 10px;color:#1f2f46;font-size:18px;line-height:1.4;">{content}</h3>'


def image_html(url: str, alt: str = "chart") -> str:
    safe_url = html.escape(url, quote=True)
    safe_alt = html.escape(alt or "chart", quote=True)
    return (
        '<p style="margin:14px 0;text-align:center;">'
        f'<img src="{safe_url}" alt="{safe_alt}" style="max-width:100%;height:auto;display:block;margin:0 auto;" />'
        "</p>"
    )


def brand_header_html(brand: str, title: str) -> str:
    return (
        '<section style="margin:0 0 22px;padding:18px 16px;border-left:5px solid #C9A227;'
        'background:#F7F3E8;">'
        f'<p style="margin:0 0 8px;color:#7A5B12;font-size:14px;font-weight:700;">{html.escape(brand)}</p>'
        f'<p style="margin:0;color:#142033;font-size:21px;font-weight:700;line-height:1.4;">{html.escape(title)}</p>'
        "</section>"
    )


def footer_html(disclaimer: str) -> str:
    if not disclaimer:
        return ""
    return (
        '<p style="margin:28px 0 0;padding-top:12px;border-top:1px solid #D9DEE7;'
        'color:#8A93A3;font-size:12px;line-height:1.6;">'
        f"{html.escape(disclaimer)}"
        "</p>"
    )


def source_report_footer_html(source_report_name: str) -> str:
    source_report_name, _stock_changes = sanitize_wechat_stock_language(source_report_name)
    source_report_name = normalize_space(source_report_name).strip(" -_.,，;；:：")
    if not source_report_name:
        return ""
    return (
        '<p style="margin:16px 0 0;color:#A3ABB8;font-size:12px;line-height:1.55;'
        'text-align:left;">'
        f"Original report: {html.escape(source_report_name)}"
        "</p>"
    )


def hook_html(text: str) -> str:
    if not text:
        return ""
    return (
        '<p style="margin:24px 0 12px;padding:14px 16px;background:#F7F3E8;'
        'border-left:4px solid #C9A227;color:#152033;font-size:16px;line-height:1.75;font-weight:600;">'
        f"{html.escape(text)}"
        "</p>"
    )


def keyword_bridge_html(keywords: list[str]) -> str:
    clean_keywords = [item for item in keywords if item][:6]
    if len(clean_keywords) < 2:
        return ""
    keyword_text = "、".join(html.escape(item) for item in clean_keywords)
    return (
        '<p style="margin:0 0 16px;color:#596579;font-size:14px;line-height:1.7;">'
        f"这篇可以沿着 <strong style=\"color:#2457A7;\">{keyword_text}</strong> 这几条线索看，"
        "重点不是复述报告，而是看这些变量如何互相验证。"
        "</p>"
    )


def referenced_markdown_image_keys(markdown: str) -> set[str]:
    keys: set[str] = set()
    for match in IMAGE_TOKEN_RE.finditer(markdown or ""):
        keys.add(f"[[KC_IMAGE_{match.group(1)}]]")
    for match in MD_IMAGE_RE.finditer(markdown or ""):
        ref = match.group(2).strip()
        if ref:
            keys.add(ref)
            keys.add(Path(ref).name)
    return keys


def after_image_note_html(text: str) -> str:
    """Follow-and-star reminder shown at the very end, after the 星球 QR image."""
    if not text:
        return ""
    return (
        '<p style="margin:16px 0 0;padding:14px 16px;background:#EAF2FB;'
        'border-left:4px solid #2E6FB7;color:#152033;font-size:15px;line-height:1.75;font-weight:600;">'
        f"{html.escape(text)}"
        "</p>"
    )


def compose_limited_html(parts: list[str], tail_parts: list[str], max_chars: int) -> str:
    tail = [part for part in tail_parts if part]
    if max_chars <= 0:
        return "\n".join(part for part in [*parts, *tail] if part)
    full = "\n".join(part for part in [*parts, *tail] if part)
    if len(full) <= max_chars:
        return full

    limited: list[str] = []
    for part in parts:
        candidate = "\n".join(item for item in [*limited, part, *tail] if item)
        if len(candidate) > max_chars:
            break
        limited.append(part)
    return "\n".join(part for part in [*limited, *tail] if part)


def content_within_limits(content: str, max_chars: int, max_bytes: int) -> bool:
    if max_chars > 0 and len(content) > max_chars:
        return False
    if max_bytes > 0 and utf8_byte_count(content) > max_bytes:
        return False
    return True


def render_fitted_wechat_html(
    markdown: str,
    title: str,
    brand: str,
    image_urls: dict[str, str],
    uploaded_images: list[dict[str, str]],
    hook_text: str,
    disclaimer: str,
    trailing_image_url: str,
    source_report_name: str,
    max_visible_chars: int,
    max_content_chars: int,
    max_content_bytes: int,
    outer_title: str = "",
) -> tuple[str, int, int, int]:
    image_limits = [len(uploaded_images)]
    for value in [2, 1, 0]:
        value = min(value, len(uploaded_images))
        if value not in image_limits:
            image_limits.append(value)
    visible_budgets = [
        max_visible_chars,
        min(max_visible_chars, 1600),
        min(max_visible_chars, 1200),
        min(max_visible_chars, 900),
        min(max_visible_chars, 650),
        min(max_visible_chars, 450),
        min(max_visible_chars, 300),
    ]
    visible_budgets = [value for idx, value in enumerate(visible_budgets) if value >= 200 and value not in visible_budgets[:idx]]

    last_content = ""
    last_visible = 0
    last_body_images = 0
    for image_limit in image_limits:
        body_images = [
            {
                "url": item["url"],
                "alt": item.get("token") or "chart",
                "source": item.get("source", ""),
                "context": item.get("context", ""),
            }
            for item in uploaded_images[:image_limit]
            if item.get("url")
        ]
        for visible_budget in visible_budgets:
            content, visible_text_chars, body_image_count = markdown_to_wechat_html(
                markdown,
                title,
                brand,
                image_urls,
                body_images,
                hook_text,
                disclaimer,
                trailing_image_url,
                source_report_name,
                visible_budget,
                max_content_chars,
                outer_title,
            )
            last_content = content
            last_visible = visible_text_chars
            last_body_images = body_image_count
            if content_within_limits(content, max_content_chars, max_content_bytes):
                return content, visible_text_chars, body_image_count, image_limit

    raise RuntimeError(
        "WeChat HTML still exceeds limits after compression: "
        f"chars={len(last_content)}, bytes={utf8_byte_count(last_content)}, "
        f"visible={last_visible}, body_images={last_body_images}, "
        f"max_chars={max_content_chars}, max_bytes={max_content_bytes}"
    )


def markdown_to_wechat_html(
    markdown: str,
    title: str,
    brand: str,
    image_urls: dict[str, str],
    body_images: list[dict[str, str]],
    hook_text: str,
    disclaimer: str,
    trailing_image_url: str,
    source_report_name: str,
    max_visible_chars: int,
    max_chars: int,
    outer_title: str = "",
) -> tuple[str, int, int]:
    title, _title_stock_changes = sanitize_wechat_stock_language(title)
    title = optimizer_clean_wechat_title(title, "", max_chars=CONTENT_HEADER_TITLE_MAX_CHARS)
    title = trim_title_complete(title.replace("…", ""), CONTENT_HEADER_TITLE_MAX_CHARS, 8)
    if len(title) < 6:
        title = "公司情况更新"
    duplicate_title_refs = title_fingerprints(title, outer_title)
    keyword_terms = extract_wechat_keywords(f"{outer_title} {title}", f"{source_report_name}\n{markdown}", max_keywords=8)
    parts: list[str] = [brand_header_html(brand, title)]
    bridge = keyword_bridge_html(keyword_terms)
    if bridge:
        parts.append(bridge)
    paragraph: list[str] = []
    list_items: list[str] = []
    rendered_image_urls: set[str] = set()
    referenced_keys = referenced_markdown_image_keys(markdown)
    floating_images = [
        item
        for item in body_images
        if item.get("url") and (item.get("alt") or "") not in referenced_keys
    ]
    floating_image_index = 0
    selected_image_urls = [item["url"] for item in body_images if item.get("url")]
    selected_image_set = set(selected_image_urls)
    body_budget = max(0, max_visible_chars - visible_char_count(hook_text))
    placement_budget = min(body_budget, max(visible_char_count(clean_markdown(markdown)), 1)) if body_budget else 0
    text_used = 0

    def remaining_chars() -> int:
        return max(0, body_budget - text_used)

    def fit_text(text: str) -> str:
        nonlocal text_used
        if body_budget <= 0 or text_used >= body_budget:
            return ""
        count = visible_char_count(text)
        if count <= remaining_chars():
            text_used += count
            return text
        if remaining_chars() < 24:
            text_used = body_budget
            return ""
        fitted = truncate_visible_text(text, remaining_chars())
        text_used = body_budget
        return fitted

    def maybe_render_image(url: str, alt: str) -> None:
        if not url or url not in selected_image_set or url in rendered_image_urls:
            return
        parts.append(image_html(url, alt=alt))
        rendered_image_urls.add(url)

    def maybe_insert_floating_image(force: bool = False) -> None:
        nonlocal floating_image_index
        if floating_image_index >= len(floating_images):
            return
        item = floating_images[floating_image_index]
        url = item.get("url") or ""
        if not url or url in rendered_image_urls:
            floating_image_index += 1
            return
        threshold = placement_budget * (floating_image_index + 1) / (len(floating_images) + 1)
        if force or body_budget <= 0 or text_used >= threshold:
            parts.append(image_html(url, alt=item.get("context") or item.get("alt") or "KC Desk"))
            rendered_image_urls.add(url)
            floating_image_index += 1

    def should_skip_body_text(text: str) -> bool:
        plain = strip_markdown_markup(text)
        if is_mid_article_cta_text(plain):
            return True
        return visible_char_count(plain) <= 90 and text_is_duplicate_title(plain, duplicate_title_refs)

    def flush_paragraph() -> None:
        nonlocal paragraph
        if paragraph:
            paragraph_text = strip_mid_article_cta_sentences(" ".join(paragraph))
            if should_skip_body_text(paragraph_text):
                paragraph = []
                return
            fitted = fit_text(paragraph_text)
            rendered = paragraph_html(fitted)
            if rendered:
                parts.append(rendered)
                maybe_insert_floating_image()
            paragraph = []

    def flush_list() -> None:
        nonlocal list_items
        if list_items:
            rendered_items = []
            for item in list_items:
                item = strip_mid_article_cta_sentences(item)
                if should_skip_body_text(item):
                    continue
                fitted = fit_text(item)
                if fitted:
                    rendered_items.append(fitted)
                if text_used >= body_budget:
                    break
            if rendered_items:
                body = "".join(f"<li>{inline_markdown(item, context='list')}</li>" for item in rendered_items)
                parts.append(f'<ul style="margin:10px 0 12px;padding-left:22px;line-height:1.7;color:#202631;font-size:16px;">{body}</ul>')
                maybe_insert_floating_image()
            list_items = []

    for raw in clean_markdown(markdown).splitlines():
        line = raw.strip()
        if not line:
            flush_paragraph()
            flush_list()
            continue

        if line.startswith(">"):
            flush_paragraph()
            flush_list()
            quote = normalize_space(re.sub(r"^>\s?", "", line))
            quote = strip_mid_article_cta_sentences(quote)
            if should_skip_body_text(quote):
                continue
            fitted = fit_text(quote)
            if fitted:
                parts.append(kc_comment_html(fitted))
                maybe_insert_floating_image()
            continue

        token_match = IMAGE_TOKEN_RE.fullmatch(line)
        md_image_match = MD_IMAGE_RE.fullmatch(line)
        if token_match:
            flush_paragraph()
            flush_list()
            token = f"[[KC_IMAGE_{token_match.group(1)}]]"
            url = image_urls.get(token)
            maybe_render_image(url or "", token)
            maybe_insert_floating_image()
            continue
        if md_image_match:
            flush_paragraph()
            flush_list()
            ref = md_image_match.group(2).strip()
            url = image_urls.get(ref) or ref
            if url.startswith("http://") or url.startswith("https://"):
                maybe_render_image(url, md_image_match.group(1))
                maybe_insert_floating_image()
            continue

        if is_figure_meta_line(line):
            flush_paragraph()
            flush_list()
            continue

        heading = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading:
            flush_paragraph()
            flush_list()
            if should_skip_body_text(heading.group(2)):
                continue
            fitted = fit_text(heading.group(2))
            if fitted:
                parts.append(heading_html(len(heading.group(1)), fitted))
                maybe_insert_floating_image()
            continue

        bullet = re.match(r"^[-*]\s+(.+)$", line)
        if bullet:
            flush_paragraph()
            bullet_text = strip_mid_article_cta_sentences(bullet.group(1))
            if not should_skip_body_text(bullet_text):
                list_items.append(bullet_text)
            continue

        if should_skip_body_text(line):
            flush_paragraph()
            flush_list()
            continue
        paragraph.append(line)

    flush_paragraph()
    flush_list()
    while floating_image_index < len(floating_images):
        maybe_insert_floating_image(force=True)
    supplemental_images = [
        image_html(item["url"], alt=item.get("alt") or "KC Desk")
        for item in body_images
        if item.get("url") and item["url"] not in rendered_image_urls
    ]
    tail = [*supplemental_images, hook_html(hook_text), footer_html(disclaimer)]
    if trailing_image_url:
        tail.append(image_html(trailing_image_url, alt="KC Desk"))
    if source_report_name:
        tail.append(source_report_footer_html(source_report_name))
    # Very end of the article: follow / add-WeChat / star reminder.
    tail.append(after_image_note_html(DEFAULT_AFTER_IMAGE_NOTE))
    content = compose_limited_html(parts, tail, max_chars)
    total_visible = text_used + visible_char_count(hook_text)
    return content, total_visible, len(body_images)


def resolve_asset_path(report_dir: Path, raw_path: str) -> Path | None:
    raw = (raw_path or "").strip()
    if not raw:
        return None
    path = Path(raw)
    candidates = []
    if path.is_absolute():
        candidates.append(path)
    else:
        candidates.extend(
            [
                report_dir / raw,
                report_dir / "assets" / raw,
                Path.cwd() / raw,
            ]
        )
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def resolve_repo_asset_path(raw_path: str) -> Path | None:
    raw = (raw_path or "").strip()
    if not raw:
        return None
    if raw.startswith("https://github.com/") and "/blob/" in raw:
        raw = raw.split("/blob/", 1)[1].split("/", 1)[1]
    path = Path(raw)
    candidates = [path] if path.is_absolute() else [Path.cwd() / path, path]
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def load_figure_paths(report_dir: Path) -> dict[str, Path]:
    manifest = read_json(report_dir / "figure_manifest.json")
    figures: dict[str, Path] = {}
    if not isinstance(manifest, list):
        return figures
    for item in manifest:
        if not isinstance(item, dict):
            continue
        token = str(item.get("token") or "")
        if not token:
            continue
        for key in ["relative_path", "path", "source_path"]:
            resolved = resolve_asset_path(report_dir, str(item.get(key) or ""))
            if resolved:
                figures[token] = resolved
                break
    return figures


def png_chunk(kind: bytes, data: bytes) -> bytes:
    import binascii

    checksum = binascii.crc32(kind + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", checksum)


def write_fallback_cover(path: Path, width: int = 1200, height: int = 675) -> None:
    bg = (247, 243, 232)
    ink = (20, 32, 51)
    gold = (201, 162, 39)
    rows = []
    for y in range(height):
        row = bytearray()
        for x in range(width):
            if x < 34 or 92 <= y < 114:
                color = gold
            elif y < 92:
                color = ink
            else:
                color = bg
            row.extend(color)
        rows.append(b"\x00" + bytes(row))
    raw = b"".join(rows)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + png_chunk(b"IHDR", ihdr)
        + png_chunk(b"IDAT", zlib.compress(raw, level=9))
        + png_chunk(b"IEND", b"")
    )


def save_wechat_cover_jpeg(source: Path, target: Path) -> Path:
    target.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(source) as image:
        working = image.convert("RGB")
    width, height = working.size
    if width <= 0 or height <= 0:
        raise RuntimeError(f"Invalid cover dimensions for {source}: {width}x{height}")
    source_ratio = width / height
    target_ratio = WECHAT_COVER_WIDTH / WECHAT_COVER_HEIGHT
    if source_ratio >= target_ratio:
        resized_height = WECHAT_COVER_HEIGHT
        resized_width = max(WECHAT_COVER_WIDTH, round(resized_height * source_ratio))
    else:
        resized_width = WECHAT_COVER_WIDTH
        resized_height = max(WECHAT_COVER_HEIGHT, round(resized_width / source_ratio))
    resized = working.resize((resized_width, resized_height), Image.Resampling.LANCZOS)
    left = max(0, (resized_width - WECHAT_COVER_WIDTH) // 2)
    top = max(0, (resized_height - WECHAT_COVER_HEIGHT) // 2)
    cover = resized.crop((left, top, left + WECHAT_COVER_WIDTH, top + WECHAT_COVER_HEIGHT))
    cover.save(target, format="JPEG", quality=88, optimize=True, progressive=True)
    return target


def prepare_cover_upload_image(path: Path, output_dir: Path, stem: str) -> Path:
    target = output_dir / "_assets" / f"{stem}_cover.jpg"
    try:
        return save_wechat_cover_jpeg(path, target)
    except Exception as exc:
        fallback = output_dir / "_assets" / f"{stem}_fallback_cover.png"
        write_fallback_cover(fallback, WECHAT_COVER_WIDTH, WECHAT_COVER_HEIGHT)
        log(f"Could not normalize cover image {path}: {exc}; using generated fallback cover.")
        return save_wechat_cover_jpeg(fallback, target)


def choose_cover_image(report_dir: Path, figure_paths: dict[str, Path], fallback_dir: Path) -> Path:
    for token in sorted(figure_paths):
        path = figure_paths[token]
        if path.exists() and path.suffix.lower() in {".jpg", ".jpeg", ".png", ".gif", ".bmp"}:
            return path
    fallback_dir.mkdir(parents=True, exist_ok=True)
    fallback = fallback_dir / "fallback_cover.png"
    if not fallback.exists():
        write_fallback_cover(fallback)
    return fallback


def pollinations_context_snippets(markdown: str, title: str, count: int) -> list[str]:
    if count <= 0:
        return []
    candidates: list[str] = []
    current_heading = ""
    for raw in clean_markdown(markdown).splitlines():
        line = normalize_space(strip_markdown_markup(raw))
        if not line or is_figure_meta_line(line):
            continue
        if IMAGE_TOKEN_RE.search(raw) or MD_IMAGE_RE.search(raw):
            continue
        heading = re.match(r"^#{1,6}\s+(.+)$", raw.strip())
        if heading:
            current_heading = normalize_space(strip_markdown_markup(heading.group(1)))
            continue
        line = re.sub(r"^[-*>]\s*", "", line)
        if visible_char_count(line) < 28:
            continue
        context = f"{current_heading}：{line}" if current_heading else line
        candidates.append(truncate_visible_text(context, 90, suffix=""))
    if not candidates:
        return [normalize_space(strip_markdown_markup(title))] * count
    if len(candidates) <= count:
        return candidates + [candidates[-1]] * (count - len(candidates))
    if count == 1:
        return [candidates[len(candidates) // 2]]
    picks: list[str] = []
    for idx in range(count):
        pos = round(idx * (len(candidates) - 1) / (count - 1))
        picks.append(candidates[pos])
    return picks


def pollinations_prompt(title: str, index: int, context: str = "") -> str:
    topic = normalize_space(strip_markdown_markup(title)) or "global macro and industry research"
    section_context = normalize_space(strip_markdown_markup(context))
    angle = [
        "executive strategy briefing",
        "financial research insight",
        "market intelligence discussion",
    ][(index - 1) % 3]
    context_sentence = f" Specific section context: {section_context}." if section_context else ""
    prompt = (
        f"Premium editorial image for a Chinese financial research article about {topic}. "
        f"Scene type: {angle}.{context_sentence} Photorealistic business and market research visual, "
        "human-scale context, clean composition, sophisticated lighting, white, ink and gold accents, "
        "distinct from the other article images, no readable text, no logos, no watermarks, no abstract filler."
    )
    return " ".join(prompt.split())[:1000]


def pollinations_url(prompt: str) -> str:
    query = "?width=960&height=640&enhance=true&private=true&nologo=true&safe=true&model=flux"
    return POLLINATIONS_BASE_URL + quote(prompt, safe="") + query


def write_editorial_fallback_image(path: Path, title: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    width, height = 960, 640
    bg = (247, 243, 232)
    ink = (20, 32, 51)
    gold = (201, 162, 39)
    image = Image.new("RGB", (width, height), bg)
    draw = ImageDraw.Draw(image, "RGBA")
    for y in range(height):
        shade = int(18 * y / height)
        draw.line((0, y, width, y), fill=(max(0, bg[0] - shade), max(0, bg[1] - shade), max(0, bg[2] - shade)))
    draw.rectangle((0, 0, width, 92), fill=(*ink, 245))
    draw.rectangle((0, 92, width, 110), fill=(*gold, 230))
    for idx in range(7):
        x = 95 + idx * 122
        top = 220 + (idx % 3) * 34
        draw.rounded_rectangle((x, top, x + 54, 470), radius=12, outline=(*gold, 155), width=4)
        draw.ellipse((x + 12, top - 58, x + 42, top - 28), fill=(*ink, 90))
    for idx in range(5):
        y = 535 + idx * 18
        draw.line((110, y, 850, y), fill=(*ink, 48), width=4)
    image.save(path, format="JPEG", quality=86, optimize=True)


def save_optimized_jpeg(image: Image.Image, path: Path, max_bytes: int = WECHAT_UPLOADIMG_TARGET_BYTES) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    working = image.convert("RGB")
    working.thumbnail((1280, 1280), Image.Resampling.LANCZOS)
    quality = 88
    while True:
        working.save(path, format="JPEG", quality=quality, optimize=True, progressive=True)
        if path.stat().st_size < max_bytes:
            return path
        if quality > 58:
            quality -= 8
            continue
        width, height = working.size
        if width <= 640 or height <= 420:
            return path
        working = working.resize((int(width * 0.86), int(height * 0.86)), Image.Resampling.LANCZOS)
        quality = 82


def prepare_article_upload_image(path: Path, output_dir: Path, stem: str) -> Path:
    if path.suffix.lower() in {".jpg", ".jpeg", ".png"} and path.stat().st_size < WECHAT_UPLOADIMG_MAX_BYTES:
        return path
    target = output_dir / "_assets" / f"{stem}.jpg"
    with Image.open(path) as image:
        return save_optimized_jpeg(image, target)


def download_pollinations_image(
    session: requests.Session,
    prompt: str,
    target: Path,
    timeout: int,
    title: str,
) -> tuple[Path, str, str, str]:
    url = pollinations_url(prompt)
    target.parent.mkdir(parents=True, exist_ok=True)
    last_error = ""
    for attempt in range(2):
        try:
            response = session.get(url, timeout=timeout, headers={"User-Agent": "KCDeskWeChat/1.0"})
            response.raise_for_status()
            raw_path = target.with_suffix(".raw")
            raw_path.write_bytes(response.content)
            with Image.open(raw_path) as image:
                output = save_optimized_jpeg(image, target)
            raw_path.unlink(missing_ok=True)
            return output, url, "pollinations", ""
        except Exception as exc:
            last_error = str(exc)[:300]
            time.sleep(1.5 * (attempt + 1))
    write_editorial_fallback_image(target, title)
    return target, url, "fallback", last_error


def post_wechat_json(
    session: requests.Session,
    url: str,
    payload: dict[str, Any],
    timeout: int,
    max_attempts: int = WECHAT_REQUEST_MAX_ATTEMPTS,
) -> requests.Response:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    max_attempts = max(1, max_attempts)
    label = "wechat/json"

    for attempt in range(1, max_attempts + 1):
        try:
            response = session.post(
                url,
                data=body,
                headers={"Content-Type": "application/json; charset=utf-8"},
                timeout=timeout,
            )
        except requests.RequestException as exc:
            if attempt >= max_attempts:
                raise WeChatError(f"{label} request failed after {max_attempts} attempt(s): {exc}") from exc
            sleep_before_wechat_retry(label, attempt, max_attempts, str(exc))
            continue

        if is_retryable_wechat_response(response) and attempt < max_attempts:
            sleep_before_wechat_retry(label, attempt, max_attempts, f"HTTP {response.status_code}")
            continue
        retryable_error = retryable_wechat_json_error(response)
        if retryable_error and attempt < max_attempts:
            sleep_before_wechat_retry(label, attempt, max_attempts, retryable_error)
            continue
        return response

    raise WeChatError(f"{label} request failed after {max_attempts} attempt(s)")


def get_stable_access_token(session: requests.Session, appid: str, secret: str, timeout: int) -> str:
    response = post_wechat_json(
        session,
        "https://api.weixin.qq.com/cgi-bin/stable_token",
        {"grant_type": "client_credential", "appid": appid, "secret": secret, "force_refresh": False},
        timeout,
        max_attempts=WECHAT_REQUEST_MAX_ATTEMPTS,
    )
    data = parse_wechat_json(response, "stable_token")
    token = data.get("access_token")
    if not token:
        raise WeChatError(f"stable_token did not return access_token: {data}")
    return str(token)


def parse_wechat_json(response: requests.Response, label: str) -> dict[str, Any]:
    try:
        data = response.json()
    except Exception as exc:
        snippet = normalize_space(response.text[:300])
        detail = f": {snippet}" if snippet else ""
        raise WeChatError(f"{label} returned non-JSON response: HTTP {response.status_code}{detail}") from exc
    errcode = data.get("errcode")
    if errcode not in (None, 0):
        raise WeChatError(
            f"{label} failed: errcode={errcode} errmsg={data.get('errmsg')}",
            errcode=int(errcode) if isinstance(errcode, int) or str(errcode).isdigit() else None,
            errmsg=str(data.get("errmsg") or ""),
        )
    return data


def is_retryable_wechat_response(response: requests.Response) -> bool:
    return response.status_code in WECHAT_RETRYABLE_STATUS_CODES or 500 <= response.status_code < 600


def retryable_wechat_json_error(response: requests.Response) -> str:
    try:
        data = response.json()
    except Exception:
        return ""
    errcode = data.get("errcode")
    if errcode in WECHAT_RETRYABLE_ERRCODES:
        return f"errcode={errcode} errmsg={data.get('errmsg')}"
    return ""


def retry_delay_seconds(attempt: int) -> float:
    delay = WECHAT_REQUEST_RETRY_BASE_SECONDS * (2 ** max(0, attempt - 1))
    return min(WECHAT_REQUEST_RETRY_MAX_SECONDS, delay)


def sleep_before_wechat_retry(label: str, attempt: int, max_attempts: int, reason: str) -> None:
    delay = retry_delay_seconds(attempt)
    log(f"{label}: attempt {attempt}/{max_attempts} failed ({reason}); retrying in {delay:.1f}s")
    time.sleep(delay)


def upload_wechat_file(
    session: requests.Session,
    url: str,
    path: Path,
    label: str,
    timeout: int,
) -> dict[str, Any]:
    mime = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
    max_attempts = WECHAT_REQUEST_MAX_ATTEMPTS

    for attempt in range(1, max_attempts + 1):
        try:
            with path.open("rb") as handle:
                response = session.post(url, files={"media": (path.name, handle, mime)}, timeout=timeout)
        except requests.RequestException as exc:
            if attempt >= max_attempts:
                raise WeChatError(
                    f"{label} upload failed after {max_attempts} attempt(s) for {path}: {exc}"
                ) from exc
            sleep_before_wechat_retry(label, attempt, max_attempts, str(exc))
            continue

        if is_retryable_wechat_response(response) and attempt < max_attempts:
            sleep_before_wechat_retry(label, attempt, max_attempts, f"HTTP {response.status_code}")
            continue

        try:
            return parse_wechat_json(response, label)
        except WeChatError as exc:
            if exc.errcode in WECHAT_RETRYABLE_ERRCODES and attempt < max_attempts:
                sleep_before_wechat_retry(label, attempt, max_attempts, exc.errmsg or str(exc))
                continue
            raise

    raise WeChatError(f"{label} upload failed after {max_attempts} attempt(s) for {path}")


def upload_article_image(session: requests.Session, access_token: str, path: Path, timeout: int) -> str:
    if path.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
        raise WeChatError(f"Article image must be jpg/png for uploadimg: {path}")
    if path.stat().st_size >= 1024 * 1024:
        raise WeChatError(f"Article image exceeds uploadimg 1MB limit: {path}")
    url = f"https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token={access_token}"
    data = upload_wechat_file(session, url, path, "uploadimg", timeout)
    image_url = data.get("url")
    if not image_url:
        raise WeChatError(f"uploadimg did not return url for {path}: {data}")
    return str(image_url)


def upload_cover_material(session: requests.Session, access_token: str, path: Path, timeout: int) -> str:
    url = f"https://api.weixin.qq.com/cgi-bin/material/add_material?access_token={access_token}&type=image"
    data = upload_wechat_file(session, url, path, "add_material", timeout)
    media_id = data.get("media_id")
    if not media_id:
        raise WeChatError(f"add_material did not return media_id for {path}: {data}")
    return str(media_id)


def payload_article_titles(articles: list[dict[str, Any]]) -> list[str]:
    return [normalize_space(str(item.get("title") or "")) for item in articles if item.get("title")]


def payload_article_title_keys(articles: list[dict[str, Any]]) -> list[str]:
    return [draft_title_key(title) for title in payload_article_titles(articles)]


def draft_news_items(container: dict[str, Any]) -> list[dict[str, Any]]:
    candidates: list[Any] = []
    content = container.get("content")
    if isinstance(content, dict):
        candidates.extend([content.get("news_item"), content.get("articles")])
    candidates.extend([container.get("news_item"), container.get("articles")])
    for candidate in candidates:
        if isinstance(candidate, list):
            return [item for item in candidate if isinstance(item, dict)]
    return []


def batchget_recent_drafts(session: requests.Session, access_token: str, timeout: int, limit: int = 100) -> list[dict[str, Any]]:
    drafts: list[dict[str, Any]] = []
    page_size = 20
    for offset in range(0, max(1, limit), page_size):
        response = post_wechat_json(
            session,
            f"https://api.weixin.qq.com/cgi-bin/draft/batchget?access_token={access_token}",
            {"offset": offset, "count": min(page_size, limit - offset), "no_content": 0},
            timeout,
            max_attempts=WECHAT_REQUEST_MAX_ATTEMPTS,
        )
        data = parse_wechat_json(response, "draft/batchget")
        items = data.get("item")
        if not isinstance(items, list) or not items:
            break
        drafts.extend(item for item in items if isinstance(item, dict))
        total_count = data.get("total_count")
        if isinstance(total_count, int) and offset + len(items) >= total_count:
            break
        if len(drafts) >= limit:
            break
    return drafts[:limit]


def find_recent_draft_by_titles(
    session: requests.Session,
    access_token: str,
    expected_titles: list[str],
    timeout: int,
    limit: int = 100,
) -> str:
    if not expected_titles:
        return ""
    expected_keys = [draft_title_key(title) for title in expected_titles]
    try:
        recent_items = batchget_recent_drafts(session, access_token, timeout, limit=limit)
    except WeChatError as exc:
        log(f"Could not batchget recent drafts while recovering draft/add: {exc}")
        return ""
    for item in recent_items:
        if not isinstance(item, dict):
            continue
        media_id = str(item.get("media_id") or "")
        news_items = draft_news_items(item)
        titles = [normalize_space(str(news.get("title") or "")) for news in news_items]
        title_keys = [draft_title_key(title) for title in titles]
        if media_id and title_keys == expected_keys:
            return media_id
    return ""


def recover_draft_after_ambiguous_add(
    session: requests.Session,
    access_token: str,
    articles: list[dict[str, Any]],
    timeout: int,
) -> str:
    expected_titles = payload_article_titles(articles)
    for attempt in range(1, 4):
        time.sleep(min(2.0 * attempt, 5.0))
        media_id = find_recent_draft_by_titles(session, access_token, expected_titles, timeout)
        if media_id:
            log(f"Recovered draft/add media_id from recent drafts after ambiguous response: {media_id}")
            return media_id
    return ""


def add_draft(session: requests.Session, access_token: str, articles: list[dict[str, Any]], timeout: int) -> str:
    url = f"https://api.weixin.qq.com/cgi-bin/draft/add?access_token={access_token}"
    payload = {"articles": articles}
    max_attempts = WECHAT_REQUEST_MAX_ATTEMPTS
    for attempt in range(1, max_attempts + 1):
        try:
            response = post_wechat_json(session, url, payload, timeout, max_attempts=1)
            data = parse_wechat_json(response, "draft/add")
            media_id = data.get("media_id")
            if not media_id:
                raise WeChatError(f"draft/add did not return media_id: {data}")
            return str(media_id)
        except WeChatError as exc:
            if "non-JSON response" in str(exc):
                media_id = recover_draft_after_ambiguous_add(session, access_token, articles, timeout)
                if media_id:
                    return media_id
            if is_article_size_error(exc) or attempt >= max_attempts:
                raise
            if exc.errcode not in WECHAT_RETRYABLE_ERRCODES and "request failed" not in str(exc) and "non-JSON response" not in str(exc):
                raise
            sleep_before_wechat_retry("draft/add", attempt, max_attempts, exc.errmsg or str(exc))
    raise WeChatError(f"draft/add failed after {max_attempts} attempt(s)")


def get_draft(session: requests.Session, access_token: str, media_id: str, timeout: int) -> dict[str, Any]:
    response = post_wechat_json(
        session,
        f"https://api.weixin.qq.com/cgi-bin/draft/get?access_token={access_token}",
        {"media_id": media_id},
        timeout,
        max_attempts=WECHAT_REQUEST_MAX_ATTEMPTS,
    )
    return parse_wechat_json(response, "draft/get")


def summarize_draft_get_response(data: dict[str, Any], expected_article_count: int) -> dict[str, Any]:
    news_items = data.get("news_item")
    if not isinstance(news_items, list):
        news_items = data.get("articles")
    if not isinstance(news_items, list):
        news_items = []

    titles = [
        normalize_space(str(item.get("title") or ""))
        for item in news_items
        if isinstance(item, dict)
    ]
    article_count = len(news_items)
    return {
        "ok": True,
        "article_count": article_count,
        "expected_article_count": expected_article_count,
        "matches_expected_article_count": article_count == expected_article_count,
        "titles": titles,
        "create_time": data.get("create_time"),
        "update_time": data.get("update_time"),
    }


def verify_draft_get(
    session: requests.Session,
    access_token: str,
    media_id: str,
    timeout: int,
    expected_article_count: int,
) -> dict[str, Any]:
    try:
        summary = summarize_draft_get_response(
            get_draft(session, access_token, media_id, timeout),
            expected_article_count,
        )
    except WeChatError as exc:
        summary = {
            "ok": False,
            "expected_article_count": expected_article_count,
            "errcode": exc.errcode,
            "errmsg": exc.errmsg,
            "error": str(exc),
        }
        log(f"Draft get verification failed for media_id={media_id}: {exc}")
        return summary

    log(
        "Verified draft/get: "
        f"media_id={media_id} articles={summary['article_count']}/{expected_article_count}"
    )
    return summary


def submit_publish(session: requests.Session, access_token: str, media_id: str, timeout: int) -> str:
    response = post_wechat_json(
        session,
        f"https://api.weixin.qq.com/cgi-bin/freepublish/submit?access_token={access_token}",
        {"media_id": media_id},
        timeout,
        max_attempts=WECHAT_REQUEST_MAX_ATTEMPTS,
    )
    data = parse_wechat_json(response, "freepublish/submit")
    publish_id = data.get("publish_id")
    if not publish_id:
        raise WeChatError(f"freepublish/submit did not return publish_id: {data}")
    return str(publish_id)


def fake_image_url(report_dir: Path, token: str) -> str:
    safe = quote(f"{report_dir.name}-{token}", safe="")
    return f"https://example.com/wechat-dry-run/{safe}.jpg"


def fake_static_image_url(path: str) -> str:
    safe = quote(path or "trailing-image", safe="")
    return f"https://example.com/wechat-dry-run/static/{safe}"


def translated_article_title_metadata(
    report_dir: Path,
    markdown: str | None = None,
    status: dict[str, Any] | list[Any] | None = None,
) -> dict[str, str]:
    if markdown is None:
        markdown = (report_dir / "translated.md").read_text(encoding="utf-8", errors="ignore")
    if status is None:
        status = read_json(report_dir / "translation_status.json")
    fallback_title = report_dir.name
    if isinstance(status, dict):
        fallback_title = str(status.get("title") or fallback_title)
    institution_name = infer_institution_name(report_dir.name, status, markdown[:1200])
    source_report_name = source_report_name_from_translated_dir(report_dir, status)
    raw_title = title_from_markdown(markdown, fallback_title)
    title = sharpen_wechat_title(
        ensure_title_has_institution(raw_title, institution_name),
        institution_name,
    )
    wechat_title = fit_wechat_title(title, institution_name)
    header_title = content_header_title(raw_title, wechat_title)
    return {
        "report_dir": str(report_dir),
        "raw_title": raw_title,
        "title": title,
        "wechat_title": wechat_title,
        "header_title": header_title,
        "institution_name": institution_name,
        "source_report_name": source_report_name,
    }


def build_article(
    report_dir: Path,
    index: int,
    args: argparse.Namespace,
    session: requests.Session | None,
    access_token: str | None,
    output_dir: Path,
    trailing_image_url: str,
) -> dict[str, Any]:
    translated_path = report_dir / "translated.md"
    markdown, stock_changes = sanitize_wechat_stock_language(translated_path.read_text(encoding="utf-8", errors="ignore"))
    if stock_changes:
        log(f"Sanitized stock wording for {report_dir.name}: {len(stock_changes)} change(s).")
    status = read_json(report_dir / "translation_status.json")
    title_metadata = translated_article_title_metadata(report_dir, markdown, status)
    institution_name = title_metadata["institution_name"]
    source_report_name = title_metadata["source_report_name"]
    title = title_metadata["title"]
    wechat_title = title_metadata["wechat_title"]
    header_title = title_metadata["header_title"]
    figure_paths = load_figure_paths(report_dir)

    tokens = []
    for match in IMAGE_TOKEN_RE.finditer(markdown):
        token = f"[[KC_IMAGE_{match.group(1)}]]"
        if token not in tokens:
            tokens.append(token)
    tokens = tokens[: args.max_inline_images]

    image_urls: dict[str, str] = {}
    uploaded_images: list[dict[str, str]] = []
    for token in tokens:
        path = figure_paths.get(token)
        if not path:
            continue
        if args.dry_run:
            image_url = fake_image_url(report_dir, token)
            upload_path = path
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            upload_path = prepare_article_upload_image(path, output_dir, f"article_{index:02d}_{token.strip('[]').lower()}")
            image_url = upload_article_image(session, access_token, upload_path, args.timeout)
            pacing_sleep(f"After uploading inline image {index}:{token}", args.image_upload_delay_seconds, args.dry_run)
        image_urls[token] = image_url
        uploaded_images.append({"token": token, "path": str(upload_path), "url": image_url, "source": "mineru"})

    target_min_images = min(args.min_inline_images, args.max_inline_images)
    ai_image_index = 1
    ai_contexts = pollinations_context_snippets(markdown, title, target_min_images)
    while len(uploaded_images) < target_min_images:
        ai_token = f"KC_AI_IMAGE_{ai_image_index:03d}"
        context = ai_contexts[(ai_image_index - 1) % len(ai_contexts)] if ai_contexts else ""
        prompt = pollinations_prompt(title, ai_image_index, context)
        source_url = pollinations_url(prompt)
        if args.dry_run:
            image_url = fake_static_image_url(f"pollinations/{report_dir.name}/{ai_token}.jpg")
            ai_path = ""
            status_name = "dry_run"
            reason = ""
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            ai_path_obj, source_url, status_name, reason = download_pollinations_image(
                session,
                prompt,
                output_dir / "_assets" / f"article_{index:02d}_{ai_token.lower()}.jpg",
                min(args.timeout, 45),
                title,
            )
            ai_path = str(ai_path_obj)
            image_url = upload_article_image(session, access_token, ai_path_obj, args.timeout)
            pacing_sleep(f"After uploading AI image {index}:{ai_token}", args.image_upload_delay_seconds, args.dry_run)
        uploaded_images.append(
            {
                "token": ai_token,
                "path": ai_path,
                "url": image_url,
                "source": status_name,
                "prompt": prompt,
                "context": context,
                "pollinations_url": source_url,
                "reason": reason,
            }
        )
        ai_image_index += 1

    cover_image = choose_cover_image(report_dir, figure_paths, output_dir / "_assets")
    if not figure_paths:
        for item in uploaded_images:
            candidate = Path(item.get("path") or "")
            if candidate.exists() and candidate.is_file():
                cover_image = candidate
                break
    cover_image = prepare_cover_upload_image(cover_image, output_dir, f"article_{index:02d}")
    if args.dry_run:
        thumb_media_id = f"DRY_RUN_THUMB_{index:02d}"
    else:
        if session is None or access_token is None:
            raise RuntimeError("session and access_token are required outside dry-run")
        thumb_media_id = upload_cover_material(session, access_token, cover_image, args.timeout)
        pacing_sleep(f"After uploading cover image {index}", args.image_upload_delay_seconds, args.dry_run)

    content, visible_text_chars, body_image_count, fitted_image_count = render_fitted_wechat_html(
        markdown,
        header_title,
        args.brand,
        image_urls,
        uploaded_images,
        args.body_hook,
        args.disclaimer,
        trailing_image_url,
        source_report_name,
        args.max_body_chars,
        args.max_content_chars,
        args.max_content_bytes,
        wechat_title,
    )
    if not content_within_limits(content, args.max_content_chars, args.max_content_bytes):
        raise RuntimeError(
            f"WeChat HTML for {report_dir.name} is {len(content)} chars / {utf8_byte_count(content)} bytes, "
            f"above --max-content-chars={args.max_content_chars} or --max-content-bytes={args.max_content_bytes}"
        )
    if fitted_image_count < len(uploaded_images):
        log(
            f"Compressed article {index}: kept {fitted_image_count}/{len(uploaded_images)} body images "
            f"to fit WeChat content limit."
        )

    article: dict[str, Any] = {
        "article_type": "news",
        "title": wechat_title,
        "author": truncate_utf8_bytes(args.author, WECHAT_AUTHOR_MAX_BYTES),
        "digest": "",
        "content": content,
        "thumb_media_id": thumb_media_id,
        "need_open_comment": 0,
        "only_fans_can_comment": 0,
        "pic_crop_235_1": WECHAT_COVER_CROP_235_1,
        "pic_crop_1_1": WECHAT_COVER_CROP_1_1,
    }
    if args.content_source_url:
        article["content_source_url"] = args.content_source_url

    return {
        "report_dir": str(report_dir),
        "translated_markdown": str(translated_path),
        "title": title,
        "wechat_title": wechat_title,
        "header_title": header_title,
        "digest": digest_from_markdown(markdown),
        "institution_name": institution_name,
        "source_report_name": source_report_name,
        "article": article,
        "cover_image": str(cover_image),
        "inline_images": uploaded_images,
        "content_chars": len(content),
        "content_bytes": utf8_byte_count(content),
        "visible_text_chars": visible_text_chars,
        "body_image_count": body_image_count,
        "ai_image_count": sum(1 for item in uploaded_images if item.get("source") != "mineru"),
    }


def chunked(items: list[Any], size: int) -> list[list[Any]]:
    return [items[idx : idx + size] for idx in range(0, len(items), size)]


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def is_article_size_error(exc: WeChatError) -> bool:
    return exc.errcode == 45008 or "article size out of limit" in str(exc).lower()


def is_cover_crop_error(exc: WeChatError) -> bool:
    return exc.errcode == 53402 or "crop" in str(exc).lower() or "裁剪" in exc.errmsg


def replacement_cover_media_id(
    session: requests.Session,
    access_token: str,
    output_dir: Path,
    draft_index: int,
    timeout: int,
) -> str:
    fallback_png = output_dir / "_assets" / f"draft_{draft_index:02d}_replacement_cover.png"
    write_fallback_cover(fallback_png, WECHAT_COVER_WIDTH, WECHAT_COVER_HEIGHT)
    fallback_jpg = prepare_cover_upload_image(fallback_png, output_dir, f"draft_{draft_index:02d}_replacement")
    return upload_cover_material(session, access_token, fallback_jpg, timeout)


def article_payload(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [dict(item["article"]) for item in items]


def main() -> int:
    parser = argparse.ArgumentParser(description="Create WeChat Official Account drafts from KC translated reports.")
    parser.add_argument("--translated-root", default="kc_translated_reports")
    parser.add_argument("--date-folder", default="latest")
    parser.add_argument("--output-root", default="wechat_drafts")
    parser.add_argument("--max-articles", default="10")
    parser.add_argument("--article-offset", type=int, default=0)
    parser.add_argument("--include-institutions", default="", help="Comma list of institution keys/names to upload, e.g. bis,imf.")
    parser.add_argument("--articles-per-draft", type=int, default=DEFAULT_ARTICLES_PER_DRAFT)
    parser.add_argument("--max-inline-images", type=int, default=DEFAULT_MIN_INLINE_IMAGES)
    parser.add_argument("--min-inline-images", type=int, default=DEFAULT_MIN_INLINE_IMAGES)
    parser.add_argument("--max-body-chars", type=int, default=DEFAULT_BODY_VISIBLE_CHARS)
    parser.add_argument("--max-content-chars", type=int, default=DEFAULT_MAX_CONTENT_CHARS)
    parser.add_argument("--max-content-bytes", type=int, default=DEFAULT_MAX_CONTENT_BYTES)
    parser.add_argument("--brand", default=BRAND)
    parser.add_argument("--author", default=AUTHOR)
    parser.add_argument("--disclaimer", default=BOTTOM_DISCLAIMER)
    parser.add_argument("--body-hook", default=DEFAULT_BODY_HOOK)
    parser.add_argument("--trailing-image", default=DEFAULT_TRAILING_IMAGE)
    parser.add_argument("--content-source-url", default="")
    parser.add_argument("--image-upload-delay-seconds", type=float, default=DEFAULT_WECHAT_IMAGE_UPLOAD_DELAY_SECONDS)
    parser.add_argument("--article-delay-seconds", type=float, default=DEFAULT_WECHAT_ARTICLE_DELAY_SECONDS)
    parser.add_argument("--draft-delay-seconds", type=float, default=DEFAULT_WECHAT_DRAFT_DELAY_SECONDS)
    parser.add_argument("--draft-verify-delay-seconds", type=float, default=DEFAULT_WECHAT_DRAFT_VERIFY_DELAY_SECONDS)
    parser.add_argument("--wechat-appid", default=os.getenv("WECHAT_MP_APPID", ""))
    parser.add_argument("--wechat-secret", default=os.getenv("WECHAT_MP_APPSECRET", ""))
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--publish", action="store_true", help="Submit each created draft for publishing.")
    parser.add_argument("--dry-run", action="store_true", help="Build payloads without calling WeChat APIs.")
    args = parser.parse_args()

    max_articles = parse_selection_limit(args.max_articles, "--max-articles")
    if args.article_offset < 0:
        raise ValueError("--article-offset must be non-negative")
    if not 1 <= args.articles_per_draft <= 9:
        raise ValueError("--articles-per-draft must be between 1 and 9")
    if args.max_inline_images < 0:
        raise ValueError("--max-inline-images must be non-negative")
    if args.min_inline_images < 0:
        raise ValueError("--min-inline-images must be non-negative")
    if args.max_body_chars < 200:
        raise ValueError("--max-body-chars must be at least 200")
    for attr in [
        "image_upload_delay_seconds",
        "article_delay_seconds",
        "draft_delay_seconds",
        "draft_verify_delay_seconds",
    ]:
        if getattr(args, attr) < 0:
            raise ValueError(f"--{attr.replace('_', '-')} must be non-negative")
    if not args.dry_run and (not args.wechat_appid or not args.wechat_secret):
        raise ValueError("WECHAT_MP_APPID and WECHAT_MP_APPSECRET are required unless --dry-run is set")

    root = Path(args.translated_root)
    date_dir = latest_date_dir(root) if args.date_folder == "latest" else root / args.date_folder
    if not date_dir.exists():
        raise RuntimeError(f"Date folder not found: {date_dir}")

    report_dirs = find_report_dirs(date_dir)
    included_institutions = parse_institution_filter(args.include_institutions)
    institution_filtered_count = 0
    if included_institutions:
        filtered_report_dirs: list[Path] = []
        for report_dir in report_dirs:
            metadata = translated_article_title_metadata(report_dir)
            if metadata["institution_name"] in included_institutions:
                filtered_report_dirs.append(report_dir)
            else:
                institution_filtered_count += 1
        report_dirs = filtered_report_dirs

    if max_articles is None:
        selected = report_dirs[args.article_offset :]
    else:
        selected = report_dirs[args.article_offset : args.article_offset + max_articles]
    if not selected:
        raise RuntimeError(f"No translated reports selected from {date_dir}")

    output_dir = Path(args.output_root) / date_dir.name
    output_dir.mkdir(parents=True, exist_ok=True)
    input_selected_count = len(selected)
    skipped_title_policy: list[dict[str, str]] = []
    allowed_selected: list[Path] = []
    for report_dir in selected:
        metadata = translated_article_title_metadata(report_dir)
        reason = wechat_title_policy_skip_reason(metadata["wechat_title"])
        if reason:
            record = dict(metadata)
            record["skip_reason"] = reason
            skipped_title_policy.append(record)
            log(
                "Skipped WeChat draft article by title policy: "
                f"{metadata['wechat_title']} ({reason})"
            )
        else:
            allowed_selected.append(report_dir)
    selected = allowed_selected

    if not selected:
        status = "skipped_institution_filter" if included_institutions and institution_filtered_count else "skipped_title_policy"
        message = (
            f"No selected translated reports matched --include-institutions={args.include_institutions} from {date_dir}"
            if status == "skipped_institution_filter"
            else f"All selected translated reports were blocked by WeChat title policy from {date_dir}"
        )
        summary_path = output_dir / "wechat_draft_summary.json"
        summary = {
            "date_folder": date_dir.name,
            "dry_run": args.dry_run,
            "publish": args.publish,
            "max_articles": "all" if max_articles is None else max_articles,
            "input_selected_count": input_selected_count,
            "selected_count": 0,
            "include_institutions": sorted(included_institutions),
            "institution_filtered_count": institution_filtered_count,
            "skipped_title_policy_count": len(skipped_title_policy),
            "skipped_title_policy": skipped_title_policy,
            "draft_count": 0,
            "status": status,
            "message": message,
            "drafts": [],
            "articles": [],
        }
        write_json(summary_path, summary)
        log(f"{message}; wrote skip summary: {summary_path}")
        return 0

    log(
        f"Selected {len(selected)} translated reports from {date_dir} "
        f"(institution_filtered={institution_filtered_count}, "
        f"skipped_title_policy={len(skipped_title_policy)}/{input_selected_count})"
    )

    session: requests.Session | None = None
    access_token: str | None = None
    if not args.dry_run:
        session = requests.Session()
        access_token = get_stable_access_token(session, args.wechat_appid, args.wechat_secret, args.timeout)
        log("Fetched WeChat access token")

    trailing_image_url = ""
    trailing_image_path = resolve_repo_asset_path(args.trailing_image)
    if args.trailing_image and not trailing_image_path:
        raise RuntimeError(f"Trailing image not found: {args.trailing_image}")
    if trailing_image_path:
        if args.dry_run:
            trailing_image_url = fake_static_image_url(str(trailing_image_path))
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            trailing_image_url = upload_article_image(session, access_token, trailing_image_path, args.timeout)
            log(f"Uploaded trailing image: {trailing_image_path}")
            pacing_sleep("After uploading trailing image", args.image_upload_delay_seconds, args.dry_run)

    built_articles = []
    for idx, report_dir in enumerate(selected, 1):
        start_time = time.monotonic()
        log(f"Building WeChat article {idx}/{len(selected)}: {report_dir.name}")
        article_item = build_article(report_dir, idx, args, session, access_token, output_dir, trailing_image_url)
        built_articles.append(article_item)
        log(
            f"Built WeChat article {idx}/{len(selected)} in {time.monotonic() - start_time:.1f}s: "
            f"{article_item['wechat_title']} "
            f"(body_images={article_item['body_image_count']}, ai_images={article_item['ai_image_count']})"
        )
        if idx < len(selected):
            pacing_sleep(f"After building WeChat article {idx}/{len(selected)}", args.article_delay_seconds, args.dry_run)

    drafts = []

    def create_draft(group: list[dict[str, Any]]) -> None:
        articles = article_payload(group)
        payload_bytes = utf8_byte_count(json.dumps({"articles": articles}, ensure_ascii=False, separators=(",", ":")))
        draft_index = len(drafts) + 1
        log(
            f"Preparing WeChat draft {draft_index}: articles={len(articles)} "
            f"payload_bytes={payload_bytes}"
        )
        if args.dry_run:
            media_id = f"DRY_RUN_DRAFT_{draft_index:02d}"
            publish_id = f"DRY_RUN_PUBLISH_{draft_index:02d}" if args.publish else ""
            reused_existing = False
            draft_get = {
                "ok": True,
                "dry_run": True,
                "article_count": len(articles),
                "expected_article_count": len(articles),
                "matches_expected_article_count": True,
                "titles": [item.get("title", "") for item in articles],
            }
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            log(f"Checking recent drafts before creating WeChat draft {draft_index}")
            existing_media_id = find_recent_draft_by_titles(
                session,
                access_token,
                payload_article_titles(articles),
                args.timeout,
            )
            if existing_media_id:
                media_id = existing_media_id
                reused_existing = True
                log(f"Reusing existing WeChat draft with the same article titles: media_id={media_id}")
            else:
                reused_existing = False
                try:
                    log(f"Creating WeChat draft {draft_index}")
                    pacing_sleep(f"Before creating WeChat draft {draft_index}", args.draft_delay_seconds, args.dry_run)
                    media_id = add_draft(session, access_token, articles, args.timeout)
                except WeChatError as exc:
                    if is_cover_crop_error(exc):
                        log(
                            "WeChat rejected a draft cover crop; replacing this draft group's "
                            "cover images with a generated safe cover and retrying."
                        )
                        safe_thumb_media_id = replacement_cover_media_id(
                            session,
                            access_token,
                            output_dir,
                            draft_index,
                            args.timeout,
                        )
                        for article in articles:
                            article["thumb_media_id"] = safe_thumb_media_id
                            article["pic_crop_235_1"] = WECHAT_COVER_CROP_235_1
                            article["pic_crop_1_1"] = WECHAT_COVER_CROP_1_1
                        pacing_sleep(f"Before retrying WeChat draft {draft_index}", args.draft_delay_seconds, args.dry_run)
                        media_id = add_draft(session, access_token, articles, args.timeout)
                    elif is_article_size_error(exc) and len(group) > 1:
                        split_at = max(1, len(group) // 2)
                        log(
                            "WeChat rejected draft group as too large; "
                            f"splitting {len(group)} articles into {split_at}+{len(group) - split_at} and retrying."
                        )
                        create_draft(group[:split_at])
                        create_draft(group[split_at:])
                        return
                    raise
            log(f"Verifying WeChat draft {draft_index}: media_id={media_id}")
            pacing_sleep(f"Before verifying WeChat draft {draft_index}", args.draft_verify_delay_seconds, args.dry_run)
            draft_get = verify_draft_get(session, access_token, media_id, args.timeout, len(articles))
            publish_id = submit_publish(session, access_token, media_id, args.timeout) if args.publish else ""

        payload_path = output_dir / f"draft_payload_{draft_index:02d}.json"
        write_json(payload_path, {"articles": articles})
        drafts.append(
            {
                "draft_index": draft_index,
                "media_id": media_id,
                "publish_id": publish_id,
                "published": bool(publish_id),
                "reused_existing": reused_existing,
                "article_count": len(articles),
                "payload_bytes": payload_bytes,
                "payload": str(payload_path),
                "titles": [item["title"] for item in group],
                "wechat_titles": [item["wechat_title"] for item in group],
                "draft_get": draft_get,
            }
        )
        if publish_id:
            log(f"Draft {draft_index}: articles={len(articles)} media_id={media_id} publish_id={publish_id}")
        else:
            log(f"Draft {draft_index}: articles={len(articles)} media_id={media_id}")

    for group in chunked(built_articles, args.articles_per_draft):
        create_draft(group)

    summary = {
        "date_folder": date_dir.name,
        "dry_run": args.dry_run,
        "publish": args.publish,
        "max_articles": "all" if max_articles is None else max_articles,
        "input_selected_count": input_selected_count,
        "selected_count": len(selected),
        "include_institutions": sorted(included_institutions),
        "institution_filtered_count": institution_filtered_count,
        "skipped_title_policy_count": len(skipped_title_policy),
        "skipped_title_policy": skipped_title_policy,
        "articles_per_draft": args.articles_per_draft,
        "draft_count": len(drafts),
        "max_body_chars": args.max_body_chars,
        "max_content_chars": args.max_content_chars,
        "max_content_bytes": args.max_content_bytes,
        "min_inline_images": args.min_inline_images,
        "max_inline_images": args.max_inline_images,
        "body_hook": args.body_hook,
        "image_upload_delay_seconds": args.image_upload_delay_seconds,
        "article_delay_seconds": args.article_delay_seconds,
        "draft_delay_seconds": args.draft_delay_seconds,
        "draft_verify_delay_seconds": args.draft_verify_delay_seconds,
        "trailing_image": str(trailing_image_path) if trailing_image_path else "",
        "drafts": drafts,
        "articles": [
            {
                "title": item["title"],
                "wechat_title": item["wechat_title"],
                "header_title": item.get("header_title", ""),
                "institution_name": item["institution_name"],
                "source_report_name": item["source_report_name"],
                "report_dir": item["report_dir"],
                "content_chars": item["content_chars"],
                "content_bytes": item["content_bytes"],
                "visible_text_chars": item["visible_text_chars"],
                "inline_image_count": len(item["inline_images"]),
                "body_image_count": item["body_image_count"],
                "ai_image_count": item["ai_image_count"],
                "cover_image": item["cover_image"],
            }
            for item in built_articles
        ],
    }
    summary_path = output_dir / "wechat_draft_summary.json"
    write_json(summary_path, summary)
    log(f"Wrote summary: {summary_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
