#!/usr/bin/env python3
"""Push KC translated Markdown reports into WeChat Official Account drafts.

The translated report workflow writes one folder per report under:

  kc_translated_reports/<date>/<report>/translated.md

This script converts those Markdown files into WeChat-compatible HTML, uploads
inline chart images through the article-image API, uploads one permanent image
material per article for the cover, and creates draft items in chunks.
"""
from __future__ import annotations

import argparse
import html
import json
import mimetypes
import os
import re
import struct
import sys
import zlib
from pathlib import Path
from typing import Any
from urllib.parse import quote

import requests


BRAND = "KC桌面——外资精译"
AUTHOR = "KC桌面"
BOTTOM_DISCLAIMER = "For informational purposes only. Not investment advice."
DATE_DIR_RE = re.compile(r"^\d{6,8}$")
IMAGE_TOKEN_RE = re.compile(r"\[\[KC_IMAGE_(\d{3})\]\]")
MD_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^\)]+)\)")
APPENDIX_RE = re.compile(
    r"^\s*#{1,6}\s*(?:附录|appendix|disclosure|disclaimer|important disclosures?|"
    r"analyst certification|重要披露|披露章节|披露|分析师认证|免责声明)\b",
    re.I,
)
TRAILING_DISCLOSURE_RE = re.compile(
    r"(?:仅供学习交流|不构成投资建议|deepseek|mineru|自动清洗|原报告作者|机构\s*logo|"
    r"translated by|generated by|"
    r"MS开展并寻求|MS\s+does and seeks|利益冲突|conflict of interest|"
    r"有关分析师认证|analyst certification|其他重要披露|important disclosures|"
    r"MS披露网站|MS Disclosure Website|投资代表|investment representative|"
    r"股价走势图|equity rating histories)",
    re.I,
)
USER_NOISE_LINE_RE = re.compile(
    r"^(?:MS亚洲有限公司\+?|MS ASIA LIMITED\+?|行业观点|Industry View|具吸引力|Attractive|"
    r"相关报告[:：].*|Related report:.*)$",
    re.I,
)


class WeChatError(RuntimeError):
    pass


def log(message: str) -> None:
    print(message, flush=True)


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def truncate_chars(text: str, max_chars: int) -> str:
    text = normalize_space(text)
    if len(text) <= max_chars:
        return text
    return text[: max(0, max_chars - 1)].rstrip() + "…"


def latest_date_dir(root: Path) -> Path:
    if not root.exists():
        raise RuntimeError(f"Translated root not found: {root}")
    candidates = [p for p in root.iterdir() if p.is_dir() and DATE_DIR_RE.match(p.name)]
    if not candidates:
        raise RuntimeError(f"No date-named folders found under {root}")
    return max(candidates, key=lambda p: int(p.name))


def find_report_dirs(date_dir: Path) -> list[Path]:
    return sorted(
        [p for p in date_dir.iterdir() if p.is_dir() and (p / "translated.md").exists()],
        key=lambda p: p.name,
    )


def read_json(path: Path) -> dict[str, Any] | list[Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="ignore"))
    except Exception:
        return None


def strip_markdown_markup(text: str) -> str:
    text = re.sub(r"^\s*#{1,6}\s*", "", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = MD_IMAGE_RE.sub("", text)
    text = IMAGE_TOKEN_RE.sub("", text)
    return normalize_space(text)


def title_from_markdown(markdown: str, fallback: str) -> str:
    headings: list[str] = []
    for raw in markdown.splitlines():
        line = raw.strip()
        if line.startswith("#"):
            title = strip_markdown_markup(line)
            if title and not APPENDIX_RE.match(line):
                headings.append(title)
        if len(headings) >= 2:
            break
    if not headings:
        return truncate_chars(fallback, 32)
    if len(headings) == 1:
        return truncate_chars(headings[0], 32)
    combined = f"{headings[0]}：{headings[1]}"
    return truncate_chars(combined, 32)


def digest_from_markdown(markdown: str) -> str:
    for raw in markdown.splitlines():
        line = strip_markdown_markup(raw)
        if len(line) >= 40 and not TRAILING_DISCLOSURE_RE.search(line):
            return truncate_chars(line, 96)
    return ""


def clean_markdown(markdown: str) -> str:
    cleaned: list[str] = []
    in_code = False
    for raw in markdown.splitlines():
        line = raw.rstrip()
        if line.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        if APPENDIX_RE.match(line):
            break
        if USER_NOISE_LINE_RE.match(normalize_space(line)):
            continue
        if TRAILING_DISCLOSURE_RE.search(line):
            break
        cleaned.append(line)
    return "\n".join(cleaned).strip()


def inline_markdown(text: str) -> str:
    escaped = html.escape(text, quote=False)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    return escaped


def paragraph_html(text: str) -> str:
    content = inline_markdown(normalize_space(text))
    if not content:
        return ""
    if re.match(r"^(?:图|表)\s*\d+[\.:：\s]", content):
        return f'<p style="margin:18px 0 8px;color:#3f4a5a;font-weight:600;">{content}</p>'
    if content.startswith("来源：") or content.lower().startswith("source:"):
        return f'<p style="margin:4px 0 16px;color:#7a8494;font-size:13px;">{content}</p>'
    return f'<p style="margin:10px 0;line-height:1.78;color:#202631;font-size:16px;">{content}</p>'


def heading_html(level: int, text: str) -> str:
    content = inline_markdown(strip_markdown_markup(text))
    if not content:
        return ""
    if level <= 1:
        return f'<h2 style="margin:24px 0 12px;color:#152033;font-size:22px;line-height:1.35;">{content}</h2>'
    return f'<h3 style="margin:22px 0 10px;color:#1f2f46;font-size:18px;line-height:1.4;">{content}</h3>'


def image_html(url: str, alt: str = "chart") -> str:
    safe_url = html.escape(url, quote=True)
    safe_alt = html.escape(alt or "chart", quote=True)
    return (
        '<p style="margin:14px 0;text-align:center;">'
        f'<img src="{safe_url}" alt="{safe_alt}" style="max-width:100%;height:auto;display:block;margin:0 auto;" />'
        "</p>"
    )


def brand_header_html(brand: str, title: str) -> str:
    return (
        '<section style="margin:0 0 22px;padding:18px 16px;border-left:5px solid #C9A227;'
        'background:#F7F3E8;">'
        f'<p style="margin:0 0 8px;color:#7A5B12;font-size:14px;font-weight:700;">{html.escape(brand)}</p>'
        f'<p style="margin:0;color:#142033;font-size:21px;font-weight:700;line-height:1.4;">{html.escape(title)}</p>'
        "</section>"
    )


def footer_html(disclaimer: str) -> str:
    if not disclaimer:
        return ""
    return (
        '<p style="margin:28px 0 0;padding-top:12px;border-top:1px solid #D9DEE7;'
        'color:#8A93A3;font-size:12px;line-height:1.6;">'
        f"{html.escape(disclaimer)}"
        "</p>"
    )


def compose_limited_html(parts: list[str], footer: str, max_chars: int) -> str:
    if max_chars <= 0:
        return "\n".join(part for part in [*parts, footer] if part)
    full = "\n".join(part for part in [*parts, footer] if part)
    if len(full) <= max_chars:
        return full

    limited: list[str] = []
    for part in parts:
        candidate = "\n".join(item for item in [*limited, part, footer] if item)
        if len(candidate) > max_chars:
            break
        limited.append(part)
    return "\n".join(part for part in [*limited, footer] if part)


def markdown_to_wechat_html(
    markdown: str,
    title: str,
    brand: str,
    image_urls: dict[str, str],
    disclaimer: str,
    max_chars: int,
) -> str:
    parts: list[str] = [brand_header_html(brand, title)]
    paragraph: list[str] = []
    list_items: list[str] = []
    rendered_image_tokens: set[str] = set()

    def flush_paragraph() -> None:
        nonlocal paragraph
        if paragraph:
            rendered = paragraph_html(" ".join(paragraph))
            if rendered:
                parts.append(rendered)
            paragraph = []

    def flush_list() -> None:
        nonlocal list_items
        if list_items:
            body = "".join(f"<li>{inline_markdown(item)}</li>" for item in list_items)
            parts.append(f'<ul style="margin:10px 0 12px;padding-left:22px;line-height:1.7;color:#202631;font-size:16px;">{body}</ul>')
            list_items = []

    for raw in clean_markdown(markdown).splitlines():
        line = raw.strip()
        if not line:
            flush_paragraph()
            flush_list()
            continue

        token_match = IMAGE_TOKEN_RE.fullmatch(line)
        md_image_match = MD_IMAGE_RE.fullmatch(line)
        if token_match:
            flush_paragraph()
            flush_list()
            token = f"[[KC_IMAGE_{token_match.group(1)}]]"
            if token in rendered_image_tokens:
                continue
            url = image_urls.get(token)
            if url:
                parts.append(image_html(url, alt=token))
                rendered_image_tokens.add(token)
            continue
        if md_image_match:
            flush_paragraph()
            flush_list()
            ref = md_image_match.group(2).strip()
            url = image_urls.get(ref) or ref
            if url.startswith("http://") or url.startswith("https://"):
                parts.append(image_html(url, alt=md_image_match.group(1)))
            continue

        heading = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading:
            flush_paragraph()
            flush_list()
            parts.append(heading_html(len(heading.group(1)), heading.group(2)))
            continue

        bullet = re.match(r"^[-*]\s+(.+)$", line)
        if bullet:
            flush_paragraph()
            list_items.append(bullet.group(1))
            continue

        paragraph.append(line)

    flush_paragraph()
    flush_list()
    return compose_limited_html(parts, footer_html(disclaimer), max_chars)


def resolve_asset_path(report_dir: Path, raw_path: str) -> Path | None:
    raw = (raw_path or "").strip()
    if not raw:
        return None
    path = Path(raw)
    candidates = []
    if path.is_absolute():
        candidates.append(path)
    else:
        candidates.extend(
            [
                report_dir / raw,
                report_dir / "assets" / raw,
                Path.cwd() / raw,
            ]
        )
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def load_figure_paths(report_dir: Path) -> dict[str, Path]:
    manifest = read_json(report_dir / "figure_manifest.json")
    figures: dict[str, Path] = {}
    if not isinstance(manifest, list):
        return figures
    for item in manifest:
        if not isinstance(item, dict):
            continue
        token = str(item.get("token") or "")
        if not token:
            continue
        for key in ["relative_path", "path", "source_path"]:
            resolved = resolve_asset_path(report_dir, str(item.get(key) or ""))
            if resolved:
                figures[token] = resolved
                break
    return figures


def png_chunk(kind: bytes, data: bytes) -> bytes:
    import binascii

    checksum = binascii.crc32(kind + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", checksum)


def write_fallback_cover(path: Path, width: int = 1200, height: int = 675) -> None:
    bg = (247, 243, 232)
    ink = (20, 32, 51)
    gold = (201, 162, 39)
    rows = []
    for y in range(height):
        row = bytearray()
        for x in range(width):
            if x < 34 or 92 <= y < 114:
                color = gold
            elif y < 92:
                color = ink
            else:
                color = bg
            row.extend(color)
        rows.append(b"\x00" + bytes(row))
    raw = b"".join(rows)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + png_chunk(b"IHDR", ihdr)
        + png_chunk(b"IDAT", zlib.compress(raw, level=9))
        + png_chunk(b"IEND", b"")
    )


def choose_cover_image(report_dir: Path, figure_paths: dict[str, Path], fallback_dir: Path) -> Path:
    for token in sorted(figure_paths):
        path = figure_paths[token]
        if path.exists() and path.suffix.lower() in {".jpg", ".jpeg", ".png", ".gif", ".bmp"}:
            return path
    fallback_dir.mkdir(parents=True, exist_ok=True)
    fallback = fallback_dir / "fallback_cover.png"
    if not fallback.exists():
        write_fallback_cover(fallback)
    return fallback


def get_stable_access_token(session: requests.Session, appid: str, secret: str, timeout: int) -> str:
    response = session.post(
        "https://api.weixin.qq.com/cgi-bin/stable_token",
        json={"grant_type": "client_credential", "appid": appid, "secret": secret, "force_refresh": False},
        timeout=timeout,
    )
    data = parse_wechat_json(response, "stable_token")
    token = data.get("access_token")
    if not token:
        raise WeChatError(f"stable_token did not return access_token: {data}")
    return str(token)


def parse_wechat_json(response: requests.Response, label: str) -> dict[str, Any]:
    try:
        data = response.json()
    except Exception as exc:
        raise WeChatError(f"{label} returned non-JSON response: HTTP {response.status_code}") from exc
    errcode = data.get("errcode")
    if errcode not in (None, 0):
        raise WeChatError(f"{label} failed: errcode={errcode} errmsg={data.get('errmsg')}")
    return data


def upload_wechat_file(
    session: requests.Session,
    url: str,
    path: Path,
    label: str,
    timeout: int,
) -> dict[str, Any]:
    mime = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
    with path.open("rb") as handle:
        response = session.post(url, files={"media": (path.name, handle, mime)}, timeout=timeout)
    return parse_wechat_json(response, label)


def upload_article_image(session: requests.Session, access_token: str, path: Path, timeout: int) -> str:
    if path.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
        raise WeChatError(f"Article image must be jpg/png for uploadimg: {path}")
    if path.stat().st_size >= 1024 * 1024:
        raise WeChatError(f"Article image exceeds uploadimg 1MB limit: {path}")
    url = f"https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token={access_token}"
    data = upload_wechat_file(session, url, path, "uploadimg", timeout)
    image_url = data.get("url")
    if not image_url:
        raise WeChatError(f"uploadimg did not return url for {path}: {data}")
    return str(image_url)


def upload_cover_material(session: requests.Session, access_token: str, path: Path, timeout: int) -> str:
    url = f"https://api.weixin.qq.com/cgi-bin/material/add_material?access_token={access_token}&type=image"
    data = upload_wechat_file(session, url, path, "add_material", timeout)
    media_id = data.get("media_id")
    if not media_id:
        raise WeChatError(f"add_material did not return media_id for {path}: {data}")
    return str(media_id)


def add_draft(session: requests.Session, access_token: str, articles: list[dict[str, Any]], timeout: int) -> str:
    response = session.post(
        f"https://api.weixin.qq.com/cgi-bin/draft/add?access_token={access_token}",
        json={"articles": articles},
        timeout=timeout,
    )
    data = parse_wechat_json(response, "draft/add")
    media_id = data.get("media_id")
    if not media_id:
        raise WeChatError(f"draft/add did not return media_id: {data}")
    return str(media_id)


def fake_image_url(report_dir: Path, token: str) -> str:
    safe = quote(f"{report_dir.name}-{token}", safe="")
    return f"https://example.com/wechat-dry-run/{safe}.jpg"


def build_article(
    report_dir: Path,
    index: int,
    args: argparse.Namespace,
    session: requests.Session | None,
    access_token: str | None,
    output_dir: Path,
) -> dict[str, Any]:
    translated_path = report_dir / "translated.md"
    markdown = translated_path.read_text(encoding="utf-8", errors="ignore")
    status = read_json(report_dir / "translation_status.json")
    fallback_title = report_dir.name
    if isinstance(status, dict):
        fallback_title = str(status.get("title") or fallback_title)
    title = title_from_markdown(markdown, fallback_title)
    figure_paths = load_figure_paths(report_dir)

    tokens = []
    for match in IMAGE_TOKEN_RE.finditer(markdown):
        token = f"[[KC_IMAGE_{match.group(1)}]]"
        if token not in tokens:
            tokens.append(token)
    tokens = tokens[: args.max_inline_images]

    image_urls: dict[str, str] = {}
    uploaded_images: list[dict[str, str]] = []
    for token in tokens:
        path = figure_paths.get(token)
        if not path:
            continue
        if args.dry_run:
            image_url = fake_image_url(report_dir, token)
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            image_url = upload_article_image(session, access_token, path, args.timeout)
        image_urls[token] = image_url
        uploaded_images.append({"token": token, "path": str(path), "url": image_url})

    cover_image = choose_cover_image(report_dir, figure_paths, output_dir / "_assets")
    if args.dry_run:
        thumb_media_id = f"DRY_RUN_THUMB_{index:02d}"
    else:
        if session is None or access_token is None:
            raise RuntimeError("session and access_token are required outside dry-run")
        thumb_media_id = upload_cover_material(session, access_token, cover_image, args.timeout)

    content = markdown_to_wechat_html(markdown, title, args.brand, image_urls, args.disclaimer, args.max_content_chars)
    if len(content) > args.max_content_chars:
        raise RuntimeError(
            f"WeChat HTML for {report_dir.name} is {len(content)} chars, "
            f"above --max-content-chars={args.max_content_chars}"
        )

    article: dict[str, Any] = {
        "article_type": "news",
        "title": title,
        "author": truncate_chars(args.author, 16),
        "digest": "",
        "content": content,
        "thumb_media_id": thumb_media_id,
        "need_open_comment": 0,
        "only_fans_can_comment": 0,
    }
    if args.content_source_url:
        article["content_source_url"] = args.content_source_url

    return {
        "report_dir": str(report_dir),
        "translated_markdown": str(translated_path),
        "title": title,
        "digest": digest_from_markdown(markdown),
        "article": article,
        "cover_image": str(cover_image),
        "inline_images": uploaded_images,
        "content_chars": len(content),
    }


def chunked(items: list[Any], size: int) -> list[list[Any]]:
    return [items[idx : idx + size] for idx in range(0, len(items), size)]


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Create WeChat Official Account drafts from KC translated reports.")
    parser.add_argument("--translated-root", default="kc_translated_reports")
    parser.add_argument("--date-folder", default="latest")
    parser.add_argument("--output-root", default="wechat_drafts")
    parser.add_argument("--max-articles", type=int, default=10)
    parser.add_argument("--article-offset", type=int, default=0)
    parser.add_argument("--articles-per-draft", type=int, default=9)
    parser.add_argument("--max-inline-images", type=int, default=28)
    parser.add_argument("--max-content-chars", type=int, default=19500)
    parser.add_argument("--brand", default=BRAND)
    parser.add_argument("--author", default=AUTHOR)
    parser.add_argument("--disclaimer", default=BOTTOM_DISCLAIMER)
    parser.add_argument("--content-source-url", default="")
    parser.add_argument("--wechat-appid", default=os.getenv("WECHAT_MP_APPID", ""))
    parser.add_argument("--wechat-secret", default=os.getenv("WECHAT_MP_APPSECRET", ""))
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--dry-run", action="store_true", help="Build payloads without calling WeChat APIs.")
    args = parser.parse_args()

    if args.max_articles < 1:
        raise ValueError("--max-articles must be at least 1")
    if not 1 <= args.articles_per_draft <= 9:
        raise ValueError("--articles-per-draft must be between 1 and 9")
    if args.max_inline_images < 0:
        raise ValueError("--max-inline-images must be non-negative")
    if not args.dry_run and (not args.wechat_appid or not args.wechat_secret):
        raise ValueError("WECHAT_MP_APPID and WECHAT_MP_APPSECRET are required unless --dry-run is set")

    root = Path(args.translated_root)
    date_dir = latest_date_dir(root) if args.date_folder == "latest" else root / args.date_folder
    if not date_dir.exists():
        raise RuntimeError(f"Date folder not found: {date_dir}")

    report_dirs = find_report_dirs(date_dir)
    selected = report_dirs[args.article_offset : args.article_offset + args.max_articles]
    if not selected:
        raise RuntimeError(f"No translated reports selected from {date_dir}")

    output_dir = Path(args.output_root) / date_dir.name
    output_dir.mkdir(parents=True, exist_ok=True)
    log(f"Selected {len(selected)} translated reports from {date_dir}")

    session: requests.Session | None = None
    access_token: str | None = None
    if not args.dry_run:
        session = requests.Session()
        access_token = get_stable_access_token(session, args.wechat_appid, args.wechat_secret, args.timeout)
        log("Fetched WeChat access token")

    built_articles = [
        build_article(report_dir, idx, args, session, access_token, output_dir)
        for idx, report_dir in enumerate(selected, 1)
    ]

    drafts = []
    for draft_index, group in enumerate(chunked(built_articles, args.articles_per_draft), 1):
        articles = []
        for item in group:
            article = dict(item["article"])
            if len(group) == 1:
                article["digest"] = item["digest"]
            articles.append(article)
        payload_path = output_dir / f"draft_payload_{draft_index:02d}.json"
        write_json(payload_path, {"articles": articles})

        if args.dry_run:
            media_id = f"DRY_RUN_DRAFT_{draft_index:02d}"
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            media_id = add_draft(session, access_token, articles, args.timeout)

        drafts.append(
            {
                "draft_index": draft_index,
                "media_id": media_id,
                "article_count": len(articles),
                "payload": str(payload_path),
                "titles": [item["title"] for item in group],
            }
        )
        log(f"Draft {draft_index}: articles={len(articles)} media_id={media_id}")

    summary = {
        "date_folder": date_dir.name,
        "dry_run": args.dry_run,
        "selected_count": len(selected),
        "articles_per_draft": args.articles_per_draft,
        "draft_count": len(drafts),
        "drafts": drafts,
        "articles": [
            {
                "title": item["title"],
                "report_dir": item["report_dir"],
                "content_chars": item["content_chars"],
                "inline_image_count": len(item["inline_images"]),
                "cover_image": item["cover_image"],
            }
            for item in built_articles
        ],
    }
    summary_path = output_dir / "wechat_draft_summary.json"
    write_json(summary_path, summary)
    log(f"Wrote summary: {summary_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
