#!/usr/bin/env python3
"""Push KC translated Markdown reports into WeChat Official Account drafts.

The translated report workflow writes one folder per report under:

  kc_translated_reports/<date>/<report>/translated.md

This script converts those Markdown files into WeChat-compatible HTML, uploads
inline chart images through the article-image API, uploads one permanent image
material per article for the cover, creates draft items in chunks, and can
optionally submit those drafts for publishing.
"""
from __future__ import annotations

import argparse
import html
import json
import mimetypes
import os
import re
import struct
import sys
import time
import zlib
from pathlib import Path
from typing import Any
from urllib.parse import quote

import requests
from PIL import Image, ImageDraw

from institution_names import ensure_title_has_institution, infer_institution_name


BRAND = "KC桌面——外资精译"
AUTHOR = "KC桌面"
BOTTOM_DISCLAIMER = "For informational purposes only. Not investment advice."
DEFAULT_BODY_HOOK = (
    "更多完整报告和后续精译，扫文末图片进群交流。每天由 AI agent + 人工 review 生成国际投行"
    "中文摘要与 KC评论，daily 更新约 10-40 页，并整理当天最新数据图表合集，方便喂给 AI，"
    "也方便人工快速把握 market dynamics。"
)
DEFAULT_BODY_VISIBLE_CHARS = 2000
DEFAULT_MIN_INLINE_IMAGES = 3
DEFAULT_ARTICLES_PER_DRAFT = 8
DEFAULT_MAX_CONTENT_CHARS = 19500
DEFAULT_MAX_CONTENT_BYTES = 18000
DISPLAY_TITLE_MAX_CHARS = 64
WECHAT_AUTHOR_MAX_BYTES = 20
WECHAT_DIGEST_MAX_BYTES = 120
WECHAT_TITLE_MAX_CHARS = 64
WECHAT_UPLOADIMG_MAX_BYTES = 1024 * 1024
WECHAT_UPLOADIMG_TARGET_BYTES = 930 * 1024
DEFAULT_TRAILING_IMAGE = "prompts/zsxq_img.jpg"
POLLINATIONS_BASE_URL = "https://image.pollinations.ai/prompt/"
WECHAT_REQUEST_MAX_ATTEMPTS = 5
WECHAT_REQUEST_RETRY_BASE_SECONDS = 1.5
WECHAT_REQUEST_RETRY_MAX_SECONDS = 20.0
WECHAT_RETRYABLE_STATUS_CODES = {408, 425, 429, 500, 502, 503, 504}
WECHAT_RETRYABLE_ERRCODES = {-1}
WECHAT_TITLE_CHINA_RE = re.compile(
    r"(中国|大陆|内地|北京|人民币|A股|港股|\bChina\b|\bChinese\b|\bMainland\b|"
    r"\bBeijing\b|\bRMB\b|\bCNY\b|Hong Kong|\bHK\b|Taiwan)",
    re.I,
)
WECHAT_TITLE_CHINA_NEGATIVE_RE = re.compile(
    r"(负面|下行|放缓|收缩|疲弱|低迷|恶化|危机|风险|压力|冲击|衰退|萎缩|通缩|失业|"
    r"违约|债务|赤字|亏损|暴跌|崩盘|崩溃|泡沫|过剩|瓶颈|缺口|短缺|限制|封锁|"
    r"拖累|警告|担忧|不确定|不及预期|risk|slowdown|slump|weak|weakness|crisis|"
    r"recession|contraction|deflation|default|debt|deficit|loss|crash|collapse|"
    r"bubble|overcapacity|bottleneck|shortage|restriction|concern|uncertain)",
    re.I,
)
WECHAT_TITLE_CHINA_POLITICAL_RE = re.compile(
    r"(政治|政策|监管|管控|管制|供给侧|改革|政府|国务院|中央|官方|当局|审查|国安|"
    r"关税|贸易战|出口管制|资本管制|制裁|禁令|politic|policy|regulation|regulatory|"
    r"government|authority|official|censorship|tariff|trade war|export control|sanction|\bban\b)",
    re.I,
)
WECHAT_TITLE_STRONG_CHINA_SENSITIVE_RE = re.compile(
    r"(中共|共产党|党中央|政治局|习近平|反腐|国安法|台湾|台海|新疆|西藏|人权|民主|"
    r"抗议|示威|镇压|南海|军事|CCP|Communist Party|Xi Jinping|Taiwan|Taiwan Strait|"
    r"Xinjiang|Tibet|human rights|democracy|protest|crackdown|South China Sea|military)",
    re.I,
)
DATE_DIR_RE = re.compile(r"^\d{6,8}$")
IMAGE_TOKEN_RE = re.compile(r"\[\[KC_IMAGE_(\d{3})\]\]")
MD_IMAGE_RE = re.compile(r"!\[([^\]]*)\]\(([^\)]+)\)")
APPENDIX_RE = re.compile(
    r"^\s*#{1,6}\s*(?:附录|appendix|disclosure|disclaimer|important disclosures?|"
    r"analyst certification|重要披露|披露章节|披露|分析师认证|免责声明)\b",
    re.I,
)
TRAILING_DISCLOSURE_RE = re.compile(
    r"(?:仅供学习交流|不构成投资建议|deepseek|mineru|自动清洗|原报告作者|机构\s*logo|"
    r"translated by|generated by|"
    r"MS开展并寻求|MS\s+does and seeks|利益冲突|conflict of interest|"
    r"有关分析师认证|analyst certification|其他重要披露|important disclosures|"
    r"MS披露网站|MS Disclosure Website|投资代表|investment representative|"
    r"股价走势图|equity rating histories)",
    re.I,
)
USER_NOISE_LINE_RE = re.compile(
    r"^(?:MS亚洲有限公司\+?|MS ASIA LIMITED\+?|行业观点|Industry View|具吸引力|Attractive|"
    r"相关报告[:：].*|Related report:.*)$",
    re.I,
)
INSTITUTION_TITLE_ALIASES: list[tuple[str, list[str]]] = [
    ("高盛", ["GS", "Goldman Sachs"]),
    ("摩根大通", ["JPM", "J.P. Morgan", "JP Morgan", "JPMorgan"]),
    ("摩根士丹利", ["MS", "Morgan Stanley", "摩根斯坦利", "大摩"]),
    ("美银", ["BofA", "Bank of America", "美国银行", "美银证券"]),
    ("花旗", ["Citi", "Citigroup"]),
    ("瑞银", ["UBS"]),
    ("汇丰", ["HSBC"]),
    ("巴克莱", ["Barclays"]),
    ("伯恩斯坦", ["Bernstein", "Sanford C. Bernstein", "Sanford Bernstein"]),
    ("德意志银行", ["DB", "Deutsche Bank", "德银"]),
    ("野村", ["Nomura"]),
    ("美联储", ["Fed", "Federal Reserve"]),
]


class WeChatError(RuntimeError):
    def __init__(self, message: str, errcode: int | None = None, errmsg: str = "") -> None:
        super().__init__(message)
        self.errcode = errcode
        self.errmsg = errmsg


def log(message: str) -> None:
    print(message, flush=True)


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def regex_matches(pattern: re.Pattern[str], text: str) -> list[str]:
    matches: list[str] = []
    for match in pattern.finditer(text or ""):
        value = normalize_space(match.group(0))
        if value and value not in matches:
            matches.append(value)
    return matches


def wechat_title_policy_skip_reason(title: str) -> str:
    normalized = normalize_space(title)
    if not normalized:
        return ""

    strong_sensitive = regex_matches(WECHAT_TITLE_STRONG_CHINA_SENSITIVE_RE, normalized)
    if strong_sensitive:
        return "china_political_sensitive_terms=" + ",".join(strong_sensitive[:6])

    china_terms = regex_matches(WECHAT_TITLE_CHINA_RE, normalized)
    if not china_terms:
        return ""

    negative_terms = regex_matches(WECHAT_TITLE_CHINA_NEGATIVE_RE, normalized)
    if negative_terms:
        return (
            "china_negative_title_terms="
            + ",".join(china_terms[:4])
            + ";negative="
            + ",".join(negative_terms[:6])
        )

    political_terms = regex_matches(WECHAT_TITLE_CHINA_POLITICAL_RE, normalized)
    if political_terms:
        return (
            "china_political_policy_terms="
            + ",".join(china_terms[:4])
            + ";sensitive="
            + ",".join(political_terms[:6])
        )

    return ""


def canonicalize_institution_title_name(title: str) -> str:
    normalized = normalize_space(title)
    normalized = normalized.replace("摩根斯坦利", "摩根士丹利")
    normalized = normalized.replace("美国银行：", "美银：")
    return normalized


def alias_pattern(alias: str) -> str:
    if re.fullmatch(r"[A-Z]{2,5}", alias):
        return rf"(?<![A-Za-z]){re.escape(alias)}(?![A-Za-z])"
    if re.fullmatch(r"[A-Za-z. ]+", alias):
        return r"\b" + re.escape(alias).replace(r"\ ", r"\s+") + r"\b"
    return re.escape(alias)


def limit_title_colons(title: str) -> str:
    cleaned = normalize_space(title).replace(":", "：")
    if "：" not in cleaned:
        return cleaned
    head, tail = cleaned.split("：", 1)
    tail = re.sub(r"\s*：\s*", "，", tail).strip(" ，")
    if not tail:
        return head.strip()
    return f"{head.strip()}：{tail}"


def remove_redundant_title_aliases(title: str) -> str:
    cleaned = canonicalize_institution_title_name(title)
    for cn_name, aliases in INSTITUTION_TITLE_ALIASES:
        alias_group = "|".join(alias_pattern(alias) for alias in aliases)
        cleaned = re.sub(
            rf"^({re.escape(cn_name)})[：:]\s*(?:{alias_group})\s*[：:：\-—]?\s*",
            rf"\1：",
            cleaned,
            flags=re.I,
        )
        cleaned = re.sub(
            rf"^(?:{alias_group})\s*[：:]\s*({re.escape(cn_name)})\s*[：:：\-—]?\s*",
            rf"\1：",
            cleaned,
            flags=re.I,
        )
        cleaned = re.sub(
            rf"^({re.escape(cn_name)})\s*(?:\(|（)\s*(?:{alias_group})\s*(?:\)|）)\s*[：:：\-—]?\s*",
            rf"\1：",
            cleaned,
            flags=re.I,
        )
    cleaned = re.sub(r"\s*[：:]\s*", "：", cleaned)
    cleaned = re.sub(r"：{2,}", "：", cleaned)
    return limit_title_colons(cleaned).strip("：: -—")


def draft_title_key(title: str) -> str:
    key = remove_redundant_title_aliases(title)
    key = re.sub(r"\s+", "", key)
    key = key.replace(":", "：")
    return key


def sharpen_wechat_title(title: str, institution_name: str = "") -> str:
    cleaned = remove_redundant_title_aliases(strip_markdown_markup(title))
    cleaned = re.sub(r"^(?:标题|微信标题)\s*[：:]\s*", "", cleaned)
    cleaned = re.sub(r"真正的变量不是", "关键不是", cleaned)
    cleaned = re.sub(r"而是企业能否", "而是能否", cleaned)
    cleaned = re.sub(r"正在经历的不是", "不是", cleaned)
    cleaned = re.sub(r"真正的分水岭", "分水岭", cleaned)
    if institution_name:
        cleaned = ensure_title_has_institution(cleaned, canonicalize_institution_title_name(institution_name))
    return truncate_chars(remove_redundant_title_aliases(cleaned), WECHAT_TITLE_MAX_CHARS)


def truncate_chars(text: str, max_chars: int) -> str:
    text = normalize_space(text)
    if len(text) <= max_chars:
        return text
    return text[: max(0, max_chars - 1)].rstrip() + "…"


def truncate_utf8_bytes(text: str, max_bytes: int, suffix: str = "…") -> str:
    text = normalize_space(text)
    if len(text.encode("utf-8")) <= max_bytes:
        return text

    suffix_bytes = suffix.encode("utf-8")
    budget = max_bytes - len(suffix_bytes)
    if budget <= 0:
        return text.encode("utf-8")[:max_bytes].decode("utf-8", errors="ignore")

    kept: list[str] = []
    used = 0
    for char in text:
        size = len(char.encode("utf-8"))
        if used + size > budget:
            break
        kept.append(char)
        used += size
    return "".join(kept).rstrip() + suffix


def visible_char_count(text: str) -> int:
    return len(re.sub(r"\s+", "", strip_markdown_markup(text or "")))


def utf8_byte_count(text: str) -> int:
    return len((text or "").encode("utf-8"))


def truncate_visible_text(text: str, max_chars: int, suffix: str = "…") -> str:
    text = normalize_space(strip_markdown_markup(text))
    if max_chars <= 0 or visible_char_count(text) <= max_chars:
        return text
    budget = max(1, max_chars - visible_char_count(suffix))
    kept: list[str] = []
    used = 0
    for char in text:
        if char.isspace():
            kept.append(char)
            continue
        if used >= budget:
            break
        kept.append(char)
        used += 1
    return normalize_space("".join(kept)).rstrip("，,。；;：:") + suffix


def latest_date_dir(root: Path) -> Path:
    if not root.exists():
        raise RuntimeError(f"Translated root not found: {root}")
    candidates = [p for p in root.iterdir() if p.is_dir() and DATE_DIR_RE.match(p.name)]
    if not candidates:
        raise RuntimeError(f"No date-named folders found under {root}")
    return max(candidates, key=lambda p: int(p.name))


def parse_selection_limit(value: str, label: str) -> int | None:
    normalized = str(value or "").strip().lower()
    if normalized in {"all", "*"}:
        return None
    try:
        limit = int(normalized)
    except ValueError as exc:
        raise ValueError(f"{label} must be a positive integer or 'all'") from exc
    if limit < 1:
        raise ValueError(f"{label} must be at least 1, or use 'all'")
    return limit


def find_report_dirs(date_dir: Path) -> list[Path]:
    return sorted(
        [p for p in date_dir.iterdir() if p.is_dir() and (p / "translated.md").exists()],
        key=lambda p: p.name,
    )


def read_json(path: Path) -> dict[str, Any] | list[Any] | None:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="ignore"))
    except Exception:
        return None


def clean_source_report_name(value: Any) -> str:
    raw = str(value or "").strip()
    if not raw:
        return ""
    name = Path(raw).name
    name = re.sub(r"\.pdf$", "", name, flags=re.I)
    name = re.sub(r"^\d{4}-", "", name)
    name = re.sub(r"\s+", " ", name.replace("_", " ")).strip(" -._")
    return name[:240]


def source_report_name_from_xhs_dir(report_dir: Path) -> str:
    status = read_json(report_dir / "status.json")
    if isinstance(status, dict):
        cleaned = clean_source_report_name(status.get("source_pdf"))
        if cleaned:
            return cleaned
    return clean_source_report_name(report_dir.name)


def source_report_name_from_translated_dir(report_dir: Path, status: dict[str, Any] | list[Any] | None) -> str:
    if isinstance(status, dict):
        for key in ["source_report_original_name", "source_pdf", "original_report_name"]:
            cleaned = clean_source_report_name(status.get(key))
            if cleaned:
                return cleaned
        source_report_dir = status.get("source_report_dir")
        if source_report_dir:
            cleaned = source_report_name_from_xhs_dir(Path(str(source_report_dir)))
            if cleaned:
                return cleaned
    return clean_source_report_name(report_dir.name)


def strip_markdown_markup(text: str) -> str:
    text = re.sub(r"^\s*#{1,6}\s*", "", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = MD_IMAGE_RE.sub("", text)
    text = IMAGE_TOKEN_RE.sub("", text)
    return normalize_space(text)


def title_from_markdown(markdown: str, fallback: str) -> str:
    headings: list[str] = []
    for raw in markdown.splitlines():
        line = raw.strip()
        if line.startswith("#"):
            title = strip_markdown_markup(line)
            if title and not APPENDIX_RE.match(line):
                headings.append(title)
        if len(headings) >= 2:
            break
    if not headings:
        return truncate_chars(fallback, DISPLAY_TITLE_MAX_CHARS)
    if len(headings) == 1:
        return truncate_chars(headings[0], DISPLAY_TITLE_MAX_CHARS)
    combined = f"{headings[0]}：{headings[1]}"
    return truncate_chars(combined, DISPLAY_TITLE_MAX_CHARS)


def digest_from_markdown(markdown: str) -> str:
    for raw in markdown.splitlines():
        line = strip_markdown_markup(raw)
        if len(line) >= 40 and not TRAILING_DISCLOSURE_RE.search(line):
            return truncate_utf8_bytes(line, WECHAT_DIGEST_MAX_BYTES)
    return ""


def clean_markdown(markdown: str) -> str:
    cleaned: list[str] = []
    in_code = False
    for raw in markdown.splitlines():
        line = raw.rstrip()
        if line.strip().startswith("```"):
            in_code = not in_code
            continue
        if in_code:
            continue
        if APPENDIX_RE.match(line):
            break
        if USER_NOISE_LINE_RE.match(normalize_space(line)):
            continue
        if TRAILING_DISCLOSURE_RE.search(line):
            break
        cleaned.append(line)
    return "\n".join(cleaned).strip()


def highlight_terms_pattern(terms: list[str]) -> re.Pattern[str]:
    parts: list[str] = []
    for term in sorted(terms, key=len, reverse=True):
        escaped = re.escape(term).replace(r"\ ", r"\s+")
        if re.fullmatch(r"[A-Za-z0-9. &+-]+", term):
            parts.append(rf"(?<![A-Za-z]){escaped}(?![A-Za-z])")
        else:
            parts.append(escaped)
    return re.compile("|".join(parts), re.I)


HIGHLIGHT_BIG_NAME_RE = highlight_terms_pattern(
    [
        "Goldman Sachs",
        "Morgan Stanley",
        "J.P. Morgan",
        "JP Morgan",
        "JPMorgan",
        "Federal Reserve",
        "Bernstein",
        "高盛",
        "摩根大通",
        "摩根士丹利",
        "摩根斯坦利",
        "美联储",
        "伯恩斯坦",
        "美银",
        "花旗",
        "瑞银",
        "汇丰",
        "巴克莱",
        "德意志银行",
        "德银",
        "野村",
        "洪灏",
        "邢自强",
        "辜朝明",
        "特朗普",
        "马斯克",
        "Goldman",
        "JPM",
        "BofA",
        "Citi",
        "UBS",
        "HSBC",
        "Fed",
        "Trump",
        "Musk",
    ]
)
HIGHLIGHT_UPSIDE_RE = highlight_terms_pattern(
    [
        "强于预期",
        "高于预期",
        "超预期",
        "触底回升",
        "预期差",
        "上修",
        "改善",
        "回升",
        "复苏",
        "加速",
        "韧性",
        "拐点",
        "催化",
        "扩张",
        "降息",
        "宽松",
        "买入",
        "增持",
    ]
)
HIGHLIGHT_RISK_RE = highlight_terms_pattern(
    [
        "低于预期",
        "不及预期",
        "下行风险",
        "下修",
        "放缓",
        "承压",
        "压力",
        "风险",
        "疲软",
        "收缩",
        "亏损",
        "违约",
        "衰退",
        "通缩",
    ]
)
HIGHLIGHT_INSIGHT_RE = highlight_terms_pattern(
    [
        "KC评论",
        "换句话说",
        "这意味着",
        "核心是",
        "关键是",
        "重点是",
        "更重要的是",
        "注意",
        "一句话",
    ]
)
HIGHLIGHT_METRIC_RE = re.compile(
    r"(?<![A-Za-z0-9])(?:\d+(?:\.\d+)?\s*(?:%|pct|bp|bps|万亿|亿元|亿美元|亿|万|倍|x|X)|"
    r"20\d{2}年?|Q[1-4]|FY\d{2,4}|[一二三四五六七八九十]+季度)(?![A-Za-z0-9])",
    re.I,
)
HIGHLIGHT_RULES: list[tuple[str, re.Pattern[str], str]] = [
    ("insight", HIGHLIGHT_INSIGHT_RE, "color:#2F8F5B;font-weight:700;text-decoration:underline;"),
    ("big_name", HIGHLIGHT_BIG_NAME_RE, "color:#2457A7;font-weight:700;"),
    ("upside", HIGHLIGHT_UPSIDE_RE, "color:#2F8F5B;font-weight:700;"),
    ("risk", HIGHLIGHT_RISK_RE, "color:#B26B00;font-weight:700;text-decoration:underline;"),
    ("metric", HIGHLIGHT_METRIC_RE, "color:#2457A7;font-weight:700;text-decoration:underline;"),
]


def highlight_text_segment(segment: str, max_highlights: int) -> str:
    output: list[str] = []
    pos = 0
    count = 0
    while pos < len(segment):
        best: tuple[int, int, str, re.Match[str]] | None = None
        for _kind, pattern, style in HIGHLIGHT_RULES:
            match = pattern.search(segment, pos)
            if not match:
                continue
            candidate = (match.start(), -(match.end() - match.start()), style, match)
            if best is None or candidate[:2] < best[:2]:
                best = candidate
        if best is None or count >= max_highlights:
            output.append(segment[pos:])
            break
        _start, _length_key, style, match = best
        if match.start() > pos:
            output.append(segment[pos : match.start()])
        matched_text = match.group(0)
        output.append(f'<span style="{style}">{matched_text}</span>')
        pos = match.end()
        count += 1
    return "".join(output)


def apply_wechat_highlights(content: str, context: str = "body") -> str:
    if not content:
        return content
    max_highlights = 5 if context == "comment" else 7
    pieces = re.split(r"(<[^>]+>)", content)
    highlighted: list[str] = []
    in_code = False
    for piece in pieces:
        if not piece:
            continue
        if piece.startswith("<") and piece.endswith(">"):
            tag = piece.lower()
            if tag.startswith("<code"):
                in_code = True
            elif tag.startswith("</code"):
                in_code = False
            highlighted.append(piece)
            continue
        highlighted.append(piece if in_code else highlight_text_segment(piece, max_highlights))
    return "".join(highlighted)


def inline_markdown(text: str, context: str = "body") -> str:
    escaped = html.escape(text, quote=False)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    return apply_wechat_highlights(escaped, context)


def paragraph_html(text: str) -> str:
    content = inline_markdown(normalize_space(text))
    if not content:
        return ""
    if re.match(r"^(?:图|表)\s*\d+[\.:：\s]", content):
        return f'<p style="margin:18px 0 8px;color:#3f4a5a;font-weight:600;">{content}</p>'
    if content.startswith("来源：") or content.lower().startswith("source:"):
        return f'<p style="margin:4px 0 16px;color:#7a8494;font-size:13px;">{content}</p>'
    return f'<p style="margin:10px 0;line-height:1.78;color:#202631;font-size:16px;">{content}</p>'


def kc_comment_html(text: str) -> str:
    content = inline_markdown(normalize_space(text), context="comment")
    if not content:
        return ""
    return (
        '<section style="margin:18px 0;padding:13px 15px;background:#F1F8F4;'
        'border-left:4px solid #2F8F5B;color:#223044;font-size:15px;line-height:1.75;">'
        f"{content}"
        "</section>"
    )


def is_figure_meta_line(text: str) -> bool:
    content = normalize_space(strip_markdown_markup(text))
    return bool(re.match(r"^(?:图|表)\s*\d+[\.:：\s]", content)) or content.startswith("来源：") or content.lower().startswith("source:")


def heading_html(level: int, text: str) -> str:
    content = inline_markdown(strip_markdown_markup(text))
    if not content:
        return ""
    if level <= 1:
        return f'<h2 style="margin:24px 0 12px;color:#152033;font-size:22px;line-height:1.35;">{content}</h2>'
    return f'<h3 style="margin:22px 0 10px;color:#1f2f46;font-size:18px;line-height:1.4;">{content}</h3>'


def image_html(url: str, alt: str = "chart") -> str:
    safe_url = html.escape(url, quote=True)
    safe_alt = html.escape(alt or "chart", quote=True)
    return (
        '<p style="margin:14px 0;text-align:center;">'
        f'<img src="{safe_url}" alt="{safe_alt}" style="max-width:100%;height:auto;display:block;margin:0 auto;" />'
        "</p>"
    )


def brand_header_html(brand: str, title: str) -> str:
    return (
        '<section style="margin:0 0 22px;padding:18px 16px;border-left:5px solid #C9A227;'
        'background:#F7F3E8;">'
        f'<p style="margin:0 0 8px;color:#7A5B12;font-size:14px;font-weight:700;">{html.escape(brand)}</p>'
        f'<p style="margin:0;color:#142033;font-size:21px;font-weight:700;line-height:1.4;">{html.escape(title)}</p>'
        "</section>"
    )


def footer_html(disclaimer: str) -> str:
    if not disclaimer:
        return ""
    return (
        '<p style="margin:28px 0 0;padding-top:12px;border-top:1px solid #D9DEE7;'
        'color:#8A93A3;font-size:12px;line-height:1.6;">'
        f"{html.escape(disclaimer)}"
        "</p>"
    )


def source_report_footer_html(source_report_name: str) -> str:
    if not source_report_name:
        return ""
    return (
        '<p style="margin:16px 0 0;color:#A3ABB8;font-size:12px;line-height:1.55;'
        'text-align:left;">'
        f"Original report: {html.escape(source_report_name)}"
        "</p>"
    )


def hook_html(text: str) -> str:
    if not text:
        return ""
    return (
        '<p style="margin:24px 0 12px;padding:14px 16px;background:#F7F3E8;'
        'border-left:4px solid #C9A227;color:#152033;font-size:16px;line-height:1.75;font-weight:600;">'
        f"{html.escape(text)}"
        "</p>"
    )


def compose_limited_html(parts: list[str], tail_parts: list[str], max_chars: int) -> str:
    tail = [part for part in tail_parts if part]
    if max_chars <= 0:
        return "\n".join(part for part in [*parts, *tail] if part)
    full = "\n".join(part for part in [*parts, *tail] if part)
    if len(full) <= max_chars:
        return full

    limited: list[str] = []
    for part in parts:
        candidate = "\n".join(item for item in [*limited, part, *tail] if item)
        if len(candidate) > max_chars:
            break
        limited.append(part)
    return "\n".join(part for part in [*limited, *tail] if part)


def content_within_limits(content: str, max_chars: int, max_bytes: int) -> bool:
    if max_chars > 0 and len(content) > max_chars:
        return False
    if max_bytes > 0 and utf8_byte_count(content) > max_bytes:
        return False
    return True


def render_fitted_wechat_html(
    markdown: str,
    title: str,
    brand: str,
    image_urls: dict[str, str],
    uploaded_images: list[dict[str, str]],
    hook_text: str,
    disclaimer: str,
    trailing_image_url: str,
    source_report_name: str,
    max_visible_chars: int,
    max_content_chars: int,
    max_content_bytes: int,
) -> tuple[str, int, int, int]:
    image_limits = [len(uploaded_images)]
    for value in [2, 1, 0]:
        value = min(value, len(uploaded_images))
        if value not in image_limits:
            image_limits.append(value)
    visible_budgets = [
        max_visible_chars,
        min(max_visible_chars, 1600),
        min(max_visible_chars, 1200),
        min(max_visible_chars, 900),
        min(max_visible_chars, 650),
        min(max_visible_chars, 450),
        min(max_visible_chars, 300),
    ]
    visible_budgets = [value for idx, value in enumerate(visible_budgets) if value >= 200 and value not in visible_budgets[:idx]]

    last_content = ""
    last_visible = 0
    last_body_images = 0
    for image_limit in image_limits:
        body_images = [
            {"url": item["url"], "alt": item.get("token") or "chart"}
            for item in uploaded_images[:image_limit]
            if item.get("url")
        ]
        for visible_budget in visible_budgets:
            content, visible_text_chars, body_image_count = markdown_to_wechat_html(
                markdown,
                title,
                brand,
                image_urls,
                body_images,
                hook_text,
                disclaimer,
                trailing_image_url,
                source_report_name,
                visible_budget,
                max_content_chars,
            )
            last_content = content
            last_visible = visible_text_chars
            last_body_images = body_image_count
            if content_within_limits(content, max_content_chars, max_content_bytes):
                return content, visible_text_chars, body_image_count, image_limit

    raise RuntimeError(
        "WeChat HTML still exceeds limits after compression: "
        f"chars={len(last_content)}, bytes={utf8_byte_count(last_content)}, "
        f"visible={last_visible}, body_images={last_body_images}, "
        f"max_chars={max_content_chars}, max_bytes={max_content_bytes}"
    )


def markdown_to_wechat_html(
    markdown: str,
    title: str,
    brand: str,
    image_urls: dict[str, str],
    body_images: list[dict[str, str]],
    hook_text: str,
    disclaimer: str,
    trailing_image_url: str,
    source_report_name: str,
    max_visible_chars: int,
    max_chars: int,
) -> tuple[str, int, int]:
    parts: list[str] = [brand_header_html(brand, title)]
    paragraph: list[str] = []
    list_items: list[str] = []
    rendered_image_urls: set[str] = set()
    selected_image_urls = [item["url"] for item in body_images if item.get("url")]
    selected_image_set = set(selected_image_urls)
    body_budget = max(0, max_visible_chars - visible_char_count(hook_text))
    text_used = 0

    def remaining_chars() -> int:
        return max(0, body_budget - text_used)

    def fit_text(text: str) -> str:
        nonlocal text_used
        if body_budget <= 0 or text_used >= body_budget:
            return ""
        count = visible_char_count(text)
        if count <= remaining_chars():
            text_used += count
            return text
        if remaining_chars() < 24:
            text_used = body_budget
            return ""
        fitted = truncate_visible_text(text, remaining_chars())
        text_used = body_budget
        return fitted

    def maybe_render_image(url: str, alt: str) -> None:
        if not url or url not in selected_image_set or url in rendered_image_urls:
            return
        parts.append(image_html(url, alt=alt))
        rendered_image_urls.add(url)

    def flush_paragraph() -> None:
        nonlocal paragraph
        if paragraph:
            fitted = fit_text(" ".join(paragraph))
            rendered = paragraph_html(fitted)
            if rendered:
                parts.append(rendered)
            paragraph = []

    def flush_list() -> None:
        nonlocal list_items
        if list_items:
            rendered_items = []
            for item in list_items:
                fitted = fit_text(item)
                if fitted:
                    rendered_items.append(fitted)
                if text_used >= body_budget:
                    break
            if rendered_items:
                body = "".join(f"<li>{inline_markdown(item, context='list')}</li>" for item in rendered_items)
                parts.append(f'<ul style="margin:10px 0 12px;padding-left:22px;line-height:1.7;color:#202631;font-size:16px;">{body}</ul>')
            list_items = []

    for raw in clean_markdown(markdown).splitlines():
        line = raw.strip()
        if not line:
            flush_paragraph()
            flush_list()
            continue

        if line.startswith(">"):
            flush_paragraph()
            flush_list()
            quote = normalize_space(re.sub(r"^>\s?", "", line))
            fitted = fit_text(quote)
            if fitted:
                parts.append(kc_comment_html(fitted))
            continue

        token_match = IMAGE_TOKEN_RE.fullmatch(line)
        md_image_match = MD_IMAGE_RE.fullmatch(line)
        if token_match:
            flush_paragraph()
            flush_list()
            token = f"[[KC_IMAGE_{token_match.group(1)}]]"
            url = image_urls.get(token)
            maybe_render_image(url or "", token)
            continue
        if md_image_match:
            flush_paragraph()
            flush_list()
            ref = md_image_match.group(2).strip()
            url = image_urls.get(ref) or ref
            if url.startswith("http://") or url.startswith("https://"):
                maybe_render_image(url, md_image_match.group(1))
            continue

        if is_figure_meta_line(line):
            flush_paragraph()
            flush_list()
            continue

        heading = re.match(r"^(#{1,6})\s+(.+)$", line)
        if heading:
            flush_paragraph()
            flush_list()
            fitted = fit_text(heading.group(2))
            if fitted:
                parts.append(heading_html(len(heading.group(1)), fitted))
            continue

        bullet = re.match(r"^[-*]\s+(.+)$", line)
        if bullet:
            flush_paragraph()
            list_items.append(bullet.group(1))
            continue

        paragraph.append(line)

    flush_paragraph()
    flush_list()
    supplemental_images = [
        image_html(item["url"], alt=item.get("alt") or "KC Desk")
        for item in body_images
        if item.get("url") and item["url"] not in rendered_image_urls
    ]
    tail = [*supplemental_images, hook_html(hook_text), footer_html(disclaimer)]
    if trailing_image_url:
        tail.append(image_html(trailing_image_url, alt="KC Desk"))
    if source_report_name:
        tail.append(source_report_footer_html(source_report_name))
    content = compose_limited_html(parts, tail, max_chars)
    total_visible = text_used + visible_char_count(hook_text)
    return content, total_visible, len(body_images)


def resolve_asset_path(report_dir: Path, raw_path: str) -> Path | None:
    raw = (raw_path or "").strip()
    if not raw:
        return None
    path = Path(raw)
    candidates = []
    if path.is_absolute():
        candidates.append(path)
    else:
        candidates.extend(
            [
                report_dir / raw,
                report_dir / "assets" / raw,
                Path.cwd() / raw,
            ]
        )
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def resolve_repo_asset_path(raw_path: str) -> Path | None:
    raw = (raw_path or "").strip()
    if not raw:
        return None
    if raw.startswith("https://github.com/") and "/blob/" in raw:
        raw = raw.split("/blob/", 1)[1].split("/", 1)[1]
    path = Path(raw)
    candidates = [path] if path.is_absolute() else [Path.cwd() / path, path]
    for candidate in candidates:
        if candidate.exists() and candidate.is_file():
            return candidate
    return None


def load_figure_paths(report_dir: Path) -> dict[str, Path]:
    manifest = read_json(report_dir / "figure_manifest.json")
    figures: dict[str, Path] = {}
    if not isinstance(manifest, list):
        return figures
    for item in manifest:
        if not isinstance(item, dict):
            continue
        token = str(item.get("token") or "")
        if not token:
            continue
        for key in ["relative_path", "path", "source_path"]:
            resolved = resolve_asset_path(report_dir, str(item.get(key) or ""))
            if resolved:
                figures[token] = resolved
                break
    return figures


def png_chunk(kind: bytes, data: bytes) -> bytes:
    import binascii

    checksum = binascii.crc32(kind + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", checksum)


def write_fallback_cover(path: Path, width: int = 1200, height: int = 675) -> None:
    bg = (247, 243, 232)
    ink = (20, 32, 51)
    gold = (201, 162, 39)
    rows = []
    for y in range(height):
        row = bytearray()
        for x in range(width):
            if x < 34 or 92 <= y < 114:
                color = gold
            elif y < 92:
                color = ink
            else:
                color = bg
            row.extend(color)
        rows.append(b"\x00" + bytes(row))
    raw = b"".join(rows)
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + png_chunk(b"IHDR", ihdr)
        + png_chunk(b"IDAT", zlib.compress(raw, level=9))
        + png_chunk(b"IEND", b"")
    )


def choose_cover_image(report_dir: Path, figure_paths: dict[str, Path], fallback_dir: Path) -> Path:
    for token in sorted(figure_paths):
        path = figure_paths[token]
        if path.exists() and path.suffix.lower() in {".jpg", ".jpeg", ".png", ".gif", ".bmp"}:
            return path
    fallback_dir.mkdir(parents=True, exist_ok=True)
    fallback = fallback_dir / "fallback_cover.png"
    if not fallback.exists():
        write_fallback_cover(fallback)
    return fallback


def pollinations_prompt(title: str, index: int) -> str:
    topic = normalize_space(strip_markdown_markup(title)) or "global macro and industry research"
    angle = [
        "executive strategy briefing",
        "financial research insight",
        "market intelligence discussion",
    ][(index - 1) % 3]
    prompt = (
        f"Premium editorial image for a Chinese financial research article about {topic}. "
        f"Scene type: {angle}. Photorealistic business and market research visual, "
        "human-scale context, clean composition, sophisticated lighting, white, ink and gold accents, "
        "no readable text, no logos, no watermarks, no charts, no abstract filler."
    )
    return " ".join(prompt.split())[:1000]


def pollinations_url(prompt: str) -> str:
    query = "?width=960&height=640&enhance=true&private=true&nologo=true&safe=true&model=flux"
    return POLLINATIONS_BASE_URL + quote(prompt, safe="") + query


def write_editorial_fallback_image(path: Path, title: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    width, height = 960, 640
    bg = (247, 243, 232)
    ink = (20, 32, 51)
    gold = (201, 162, 39)
    image = Image.new("RGB", (width, height), bg)
    draw = ImageDraw.Draw(image, "RGBA")
    for y in range(height):
        shade = int(18 * y / height)
        draw.line((0, y, width, y), fill=(max(0, bg[0] - shade), max(0, bg[1] - shade), max(0, bg[2] - shade)))
    draw.rectangle((0, 0, width, 92), fill=(*ink, 245))
    draw.rectangle((0, 92, width, 110), fill=(*gold, 230))
    for idx in range(7):
        x = 95 + idx * 122
        top = 220 + (idx % 3) * 34
        draw.rounded_rectangle((x, top, x + 54, 470), radius=12, outline=(*gold, 155), width=4)
        draw.ellipse((x + 12, top - 58, x + 42, top - 28), fill=(*ink, 90))
    for idx in range(5):
        y = 535 + idx * 18
        draw.line((110, y, 850, y), fill=(*ink, 48), width=4)
    image.save(path, format="JPEG", quality=86, optimize=True)


def save_optimized_jpeg(image: Image.Image, path: Path, max_bytes: int = WECHAT_UPLOADIMG_TARGET_BYTES) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    working = image.convert("RGB")
    working.thumbnail((1280, 1280), Image.Resampling.LANCZOS)
    quality = 88
    while True:
        working.save(path, format="JPEG", quality=quality, optimize=True, progressive=True)
        if path.stat().st_size < max_bytes:
            return path
        if quality > 58:
            quality -= 8
            continue
        width, height = working.size
        if width <= 640 or height <= 420:
            return path
        working = working.resize((int(width * 0.86), int(height * 0.86)), Image.Resampling.LANCZOS)
        quality = 82


def prepare_article_upload_image(path: Path, output_dir: Path, stem: str) -> Path:
    if path.suffix.lower() in {".jpg", ".jpeg", ".png"} and path.stat().st_size < WECHAT_UPLOADIMG_MAX_BYTES:
        return path
    target = output_dir / "_assets" / f"{stem}.jpg"
    with Image.open(path) as image:
        return save_optimized_jpeg(image, target)


def download_pollinations_image(
    session: requests.Session,
    prompt: str,
    target: Path,
    timeout: int,
    title: str,
) -> tuple[Path, str, str, str]:
    url = pollinations_url(prompt)
    target.parent.mkdir(parents=True, exist_ok=True)
    last_error = ""
    for attempt in range(2):
        try:
            response = session.get(url, timeout=timeout, headers={"User-Agent": "KCDeskWeChat/1.0"})
            response.raise_for_status()
            raw_path = target.with_suffix(".raw")
            raw_path.write_bytes(response.content)
            with Image.open(raw_path) as image:
                output = save_optimized_jpeg(image, target)
            raw_path.unlink(missing_ok=True)
            return output, url, "pollinations", ""
        except Exception as exc:
            last_error = str(exc)[:300]
            time.sleep(1.5 * (attempt + 1))
    write_editorial_fallback_image(target, title)
    return target, url, "fallback", last_error


def post_wechat_json(
    session: requests.Session,
    url: str,
    payload: dict[str, Any],
    timeout: int,
    max_attempts: int = WECHAT_REQUEST_MAX_ATTEMPTS,
) -> requests.Response:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    max_attempts = max(1, max_attempts)
    label = "wechat/json"

    for attempt in range(1, max_attempts + 1):
        try:
            response = session.post(
                url,
                data=body,
                headers={"Content-Type": "application/json; charset=utf-8"},
                timeout=timeout,
            )
        except requests.RequestException as exc:
            if attempt >= max_attempts:
                raise WeChatError(f"{label} request failed after {max_attempts} attempt(s): {exc}") from exc
            sleep_before_wechat_retry(label, attempt, max_attempts, str(exc))
            continue

        if is_retryable_wechat_response(response) and attempt < max_attempts:
            sleep_before_wechat_retry(label, attempt, max_attempts, f"HTTP {response.status_code}")
            continue
        retryable_error = retryable_wechat_json_error(response)
        if retryable_error and attempt < max_attempts:
            sleep_before_wechat_retry(label, attempt, max_attempts, retryable_error)
            continue
        return response

    raise WeChatError(f"{label} request failed after {max_attempts} attempt(s)")


def get_stable_access_token(session: requests.Session, appid: str, secret: str, timeout: int) -> str:
    response = post_wechat_json(
        session,
        "https://api.weixin.qq.com/cgi-bin/stable_token",
        {"grant_type": "client_credential", "appid": appid, "secret": secret, "force_refresh": False},
        timeout,
        max_attempts=WECHAT_REQUEST_MAX_ATTEMPTS,
    )
    data = parse_wechat_json(response, "stable_token")
    token = data.get("access_token")
    if not token:
        raise WeChatError(f"stable_token did not return access_token: {data}")
    return str(token)


def parse_wechat_json(response: requests.Response, label: str) -> dict[str, Any]:
    try:
        data = response.json()
    except Exception as exc:
        snippet = normalize_space(response.text[:300])
        detail = f": {snippet}" if snippet else ""
        raise WeChatError(f"{label} returned non-JSON response: HTTP {response.status_code}{detail}") from exc
    errcode = data.get("errcode")
    if errcode not in (None, 0):
        raise WeChatError(
            f"{label} failed: errcode={errcode} errmsg={data.get('errmsg')}",
            errcode=int(errcode) if isinstance(errcode, int) or str(errcode).isdigit() else None,
            errmsg=str(data.get("errmsg") or ""),
        )
    return data


def is_retryable_wechat_response(response: requests.Response) -> bool:
    return response.status_code in WECHAT_RETRYABLE_STATUS_CODES or 500 <= response.status_code < 600


def retryable_wechat_json_error(response: requests.Response) -> str:
    try:
        data = response.json()
    except Exception:
        return ""
    errcode = data.get("errcode")
    if errcode in WECHAT_RETRYABLE_ERRCODES:
        return f"errcode={errcode} errmsg={data.get('errmsg')}"
    return ""


def retry_delay_seconds(attempt: int) -> float:
    delay = WECHAT_REQUEST_RETRY_BASE_SECONDS * (2 ** max(0, attempt - 1))
    return min(WECHAT_REQUEST_RETRY_MAX_SECONDS, delay)


def sleep_before_wechat_retry(label: str, attempt: int, max_attempts: int, reason: str) -> None:
    delay = retry_delay_seconds(attempt)
    log(f"{label}: attempt {attempt}/{max_attempts} failed ({reason}); retrying in {delay:.1f}s")
    time.sleep(delay)


def upload_wechat_file(
    session: requests.Session,
    url: str,
    path: Path,
    label: str,
    timeout: int,
) -> dict[str, Any]:
    mime = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
    max_attempts = WECHAT_REQUEST_MAX_ATTEMPTS

    for attempt in range(1, max_attempts + 1):
        try:
            with path.open("rb") as handle:
                response = session.post(url, files={"media": (path.name, handle, mime)}, timeout=timeout)
        except requests.RequestException as exc:
            if attempt >= max_attempts:
                raise WeChatError(
                    f"{label} upload failed after {max_attempts} attempt(s) for {path}: {exc}"
                ) from exc
            sleep_before_wechat_retry(label, attempt, max_attempts, str(exc))
            continue

        if is_retryable_wechat_response(response) and attempt < max_attempts:
            sleep_before_wechat_retry(label, attempt, max_attempts, f"HTTP {response.status_code}")
            continue

        try:
            return parse_wechat_json(response, label)
        except WeChatError as exc:
            if exc.errcode in WECHAT_RETRYABLE_ERRCODES and attempt < max_attempts:
                sleep_before_wechat_retry(label, attempt, max_attempts, exc.errmsg or str(exc))
                continue
            raise

    raise WeChatError(f"{label} upload failed after {max_attempts} attempt(s) for {path}")


def upload_article_image(session: requests.Session, access_token: str, path: Path, timeout: int) -> str:
    if path.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
        raise WeChatError(f"Article image must be jpg/png for uploadimg: {path}")
    if path.stat().st_size >= 1024 * 1024:
        raise WeChatError(f"Article image exceeds uploadimg 1MB limit: {path}")
    url = f"https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token={access_token}"
    data = upload_wechat_file(session, url, path, "uploadimg", timeout)
    image_url = data.get("url")
    if not image_url:
        raise WeChatError(f"uploadimg did not return url for {path}: {data}")
    return str(image_url)


def upload_cover_material(session: requests.Session, access_token: str, path: Path, timeout: int) -> str:
    url = f"https://api.weixin.qq.com/cgi-bin/material/add_material?access_token={access_token}&type=image"
    data = upload_wechat_file(session, url, path, "add_material", timeout)
    media_id = data.get("media_id")
    if not media_id:
        raise WeChatError(f"add_material did not return media_id for {path}: {data}")
    return str(media_id)


def payload_article_titles(articles: list[dict[str, Any]]) -> list[str]:
    return [normalize_space(str(item.get("title") or "")) for item in articles if item.get("title")]


def payload_article_title_keys(articles: list[dict[str, Any]]) -> list[str]:
    return [draft_title_key(title) for title in payload_article_titles(articles)]


def draft_news_items(container: dict[str, Any]) -> list[dict[str, Any]]:
    candidates: list[Any] = []
    content = container.get("content")
    if isinstance(content, dict):
        candidates.extend([content.get("news_item"), content.get("articles")])
    candidates.extend([container.get("news_item"), container.get("articles")])
    for candidate in candidates:
        if isinstance(candidate, list):
            return [item for item in candidate if isinstance(item, dict)]
    return []


def batchget_recent_drafts(session: requests.Session, access_token: str, timeout: int, limit: int = 100) -> list[dict[str, Any]]:
    drafts: list[dict[str, Any]] = []
    page_size = 20
    for offset in range(0, max(1, limit), page_size):
        response = post_wechat_json(
            session,
            f"https://api.weixin.qq.com/cgi-bin/draft/batchget?access_token={access_token}",
            {"offset": offset, "count": min(page_size, limit - offset), "no_content": 0},
            timeout,
            max_attempts=WECHAT_REQUEST_MAX_ATTEMPTS,
        )
        data = parse_wechat_json(response, "draft/batchget")
        items = data.get("item")
        if not isinstance(items, list) or not items:
            break
        drafts.extend(item for item in items if isinstance(item, dict))
        total_count = data.get("total_count")
        if isinstance(total_count, int) and offset + len(items) >= total_count:
            break
        if len(drafts) >= limit:
            break
    return drafts[:limit]


def find_recent_draft_by_titles(
    session: requests.Session,
    access_token: str,
    expected_titles: list[str],
    timeout: int,
    limit: int = 100,
) -> str:
    if not expected_titles:
        return ""
    expected_keys = [draft_title_key(title) for title in expected_titles]
    try:
        recent_items = batchget_recent_drafts(session, access_token, timeout, limit=limit)
    except WeChatError as exc:
        log(f"Could not batchget recent drafts while recovering draft/add: {exc}")
        return ""
    for item in recent_items:
        if not isinstance(item, dict):
            continue
        media_id = str(item.get("media_id") or "")
        news_items = draft_news_items(item)
        titles = [normalize_space(str(news.get("title") or "")) for news in news_items]
        title_keys = [draft_title_key(title) for title in titles]
        if media_id and title_keys == expected_keys:
            return media_id
    return ""


def recover_draft_after_ambiguous_add(
    session: requests.Session,
    access_token: str,
    articles: list[dict[str, Any]],
    timeout: int,
) -> str:
    expected_titles = payload_article_titles(articles)
    for attempt in range(1, 4):
        time.sleep(min(2.0 * attempt, 5.0))
        media_id = find_recent_draft_by_titles(session, access_token, expected_titles, timeout)
        if media_id:
            log(f"Recovered draft/add media_id from recent drafts after ambiguous response: {media_id}")
            return media_id
    return ""


def add_draft(session: requests.Session, access_token: str, articles: list[dict[str, Any]], timeout: int) -> str:
    url = f"https://api.weixin.qq.com/cgi-bin/draft/add?access_token={access_token}"
    payload = {"articles": articles}
    max_attempts = WECHAT_REQUEST_MAX_ATTEMPTS
    for attempt in range(1, max_attempts + 1):
        try:
            response = post_wechat_json(session, url, payload, timeout, max_attempts=1)
            data = parse_wechat_json(response, "draft/add")
            media_id = data.get("media_id")
            if not media_id:
                raise WeChatError(f"draft/add did not return media_id: {data}")
            return str(media_id)
        except WeChatError as exc:
            if "non-JSON response" in str(exc):
                media_id = recover_draft_after_ambiguous_add(session, access_token, articles, timeout)
                if media_id:
                    return media_id
            if is_article_size_error(exc) or attempt >= max_attempts:
                raise
            if exc.errcode not in WECHAT_RETRYABLE_ERRCODES and "request failed" not in str(exc) and "non-JSON response" not in str(exc):
                raise
            sleep_before_wechat_retry("draft/add", attempt, max_attempts, exc.errmsg or str(exc))
    raise WeChatError(f"draft/add failed after {max_attempts} attempt(s)")


def get_draft(session: requests.Session, access_token: str, media_id: str, timeout: int) -> dict[str, Any]:
    response = post_wechat_json(
        session,
        f"https://api.weixin.qq.com/cgi-bin/draft/get?access_token={access_token}",
        {"media_id": media_id},
        timeout,
        max_attempts=WECHAT_REQUEST_MAX_ATTEMPTS,
    )
    return parse_wechat_json(response, "draft/get")


def summarize_draft_get_response(data: dict[str, Any], expected_article_count: int) -> dict[str, Any]:
    news_items = data.get("news_item")
    if not isinstance(news_items, list):
        news_items = data.get("articles")
    if not isinstance(news_items, list):
        news_items = []

    titles = [
        normalize_space(str(item.get("title") or ""))
        for item in news_items
        if isinstance(item, dict)
    ]
    article_count = len(news_items)
    return {
        "ok": True,
        "article_count": article_count,
        "expected_article_count": expected_article_count,
        "matches_expected_article_count": article_count == expected_article_count,
        "titles": titles,
        "create_time": data.get("create_time"),
        "update_time": data.get("update_time"),
    }


def verify_draft_get(
    session: requests.Session,
    access_token: str,
    media_id: str,
    timeout: int,
    expected_article_count: int,
) -> dict[str, Any]:
    try:
        summary = summarize_draft_get_response(
            get_draft(session, access_token, media_id, timeout),
            expected_article_count,
        )
    except WeChatError as exc:
        summary = {
            "ok": False,
            "expected_article_count": expected_article_count,
            "errcode": exc.errcode,
            "errmsg": exc.errmsg,
            "error": str(exc),
        }
        log(f"Draft get verification failed for media_id={media_id}: {exc}")
        return summary

    log(
        "Verified draft/get: "
        f"media_id={media_id} articles={summary['article_count']}/{expected_article_count}"
    )
    return summary


def submit_publish(session: requests.Session, access_token: str, media_id: str, timeout: int) -> str:
    response = post_wechat_json(
        session,
        f"https://api.weixin.qq.com/cgi-bin/freepublish/submit?access_token={access_token}",
        {"media_id": media_id},
        timeout,
        max_attempts=WECHAT_REQUEST_MAX_ATTEMPTS,
    )
    data = parse_wechat_json(response, "freepublish/submit")
    publish_id = data.get("publish_id")
    if not publish_id:
        raise WeChatError(f"freepublish/submit did not return publish_id: {data}")
    return str(publish_id)


def fake_image_url(report_dir: Path, token: str) -> str:
    safe = quote(f"{report_dir.name}-{token}", safe="")
    return f"https://example.com/wechat-dry-run/{safe}.jpg"


def fake_static_image_url(path: str) -> str:
    safe = quote(path or "trailing-image", safe="")
    return f"https://example.com/wechat-dry-run/static/{safe}"


def translated_article_title_metadata(
    report_dir: Path,
    markdown: str | None = None,
    status: dict[str, Any] | list[Any] | None = None,
) -> dict[str, str]:
    if markdown is None:
        markdown = (report_dir / "translated.md").read_text(encoding="utf-8", errors="ignore")
    if status is None:
        status = read_json(report_dir / "translation_status.json")
    fallback_title = report_dir.name
    if isinstance(status, dict):
        fallback_title = str(status.get("title") or fallback_title)
    institution_name = infer_institution_name(report_dir.name, status, markdown[:1200])
    source_report_name = source_report_name_from_translated_dir(report_dir, status)
    title = sharpen_wechat_title(
        ensure_title_has_institution(title_from_markdown(markdown, fallback_title), institution_name),
        institution_name,
    )
    wechat_title = truncate_chars(title, WECHAT_TITLE_MAX_CHARS)
    return {
        "report_dir": str(report_dir),
        "title": title,
        "wechat_title": wechat_title,
        "institution_name": institution_name,
        "source_report_name": source_report_name,
    }


def build_article(
    report_dir: Path,
    index: int,
    args: argparse.Namespace,
    session: requests.Session | None,
    access_token: str | None,
    output_dir: Path,
    trailing_image_url: str,
) -> dict[str, Any]:
    translated_path = report_dir / "translated.md"
    markdown = translated_path.read_text(encoding="utf-8", errors="ignore")
    status = read_json(report_dir / "translation_status.json")
    title_metadata = translated_article_title_metadata(report_dir, markdown, status)
    institution_name = title_metadata["institution_name"]
    source_report_name = title_metadata["source_report_name"]
    title = title_metadata["title"]
    wechat_title = title_metadata["wechat_title"]
    figure_paths = load_figure_paths(report_dir)

    tokens = []
    for match in IMAGE_TOKEN_RE.finditer(markdown):
        token = f"[[KC_IMAGE_{match.group(1)}]]"
        if token not in tokens:
            tokens.append(token)
    tokens = tokens[: args.max_inline_images]

    image_urls: dict[str, str] = {}
    uploaded_images: list[dict[str, str]] = []
    for token in tokens:
        path = figure_paths.get(token)
        if not path:
            continue
        if args.dry_run:
            image_url = fake_image_url(report_dir, token)
            upload_path = path
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            upload_path = prepare_article_upload_image(path, output_dir, f"article_{index:02d}_{token.strip('[]').lower()}")
            image_url = upload_article_image(session, access_token, upload_path, args.timeout)
        image_urls[token] = image_url
        uploaded_images.append({"token": token, "path": str(upload_path), "url": image_url, "source": "mineru"})

    target_min_images = min(args.min_inline_images, args.max_inline_images)
    ai_image_index = 1
    while len(uploaded_images) < target_min_images:
        ai_token = f"KC_AI_IMAGE_{ai_image_index:03d}"
        prompt = pollinations_prompt(title, ai_image_index)
        source_url = pollinations_url(prompt)
        if args.dry_run:
            image_url = fake_static_image_url(f"pollinations/{report_dir.name}/{ai_token}.jpg")
            ai_path = ""
            status_name = "dry_run"
            reason = ""
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            ai_path_obj, source_url, status_name, reason = download_pollinations_image(
                session,
                prompt,
                output_dir / "_assets" / f"article_{index:02d}_{ai_token.lower()}.jpg",
                min(args.timeout, 45),
                title,
            )
            ai_path = str(ai_path_obj)
            image_url = upload_article_image(session, access_token, ai_path_obj, args.timeout)
        uploaded_images.append(
            {
                "token": ai_token,
                "path": ai_path,
                "url": image_url,
                "source": status_name,
                "prompt": prompt,
                "pollinations_url": source_url,
                "reason": reason,
            }
        )
        ai_image_index += 1

    cover_image = choose_cover_image(report_dir, figure_paths, output_dir / "_assets")
    if not figure_paths:
        for item in uploaded_images:
            candidate = Path(item.get("path") or "")
            if candidate.exists() and candidate.is_file():
                cover_image = candidate
                break
    if args.dry_run:
        thumb_media_id = f"DRY_RUN_THUMB_{index:02d}"
    else:
        if session is None or access_token is None:
            raise RuntimeError("session and access_token are required outside dry-run")
        thumb_media_id = upload_cover_material(session, access_token, cover_image, args.timeout)

    content, visible_text_chars, body_image_count, fitted_image_count = render_fitted_wechat_html(
        markdown,
        title,
        args.brand,
        image_urls,
        uploaded_images,
        args.body_hook,
        args.disclaimer,
        trailing_image_url,
        source_report_name,
        args.max_body_chars,
        args.max_content_chars,
        args.max_content_bytes,
    )
    if not content_within_limits(content, args.max_content_chars, args.max_content_bytes):
        raise RuntimeError(
            f"WeChat HTML for {report_dir.name} is {len(content)} chars / {utf8_byte_count(content)} bytes, "
            f"above --max-content-chars={args.max_content_chars} or --max-content-bytes={args.max_content_bytes}"
        )
    if fitted_image_count < len(uploaded_images):
        log(
            f"Compressed article {index}: kept {fitted_image_count}/{len(uploaded_images)} body images "
            f"to fit WeChat content limit."
        )

    article: dict[str, Any] = {
        "article_type": "news",
        "title": wechat_title,
        "author": truncate_utf8_bytes(args.author, WECHAT_AUTHOR_MAX_BYTES),
        "digest": "",
        "content": content,
        "thumb_media_id": thumb_media_id,
        "need_open_comment": 0,
        "only_fans_can_comment": 0,
    }
    if args.content_source_url:
        article["content_source_url"] = args.content_source_url

    return {
        "report_dir": str(report_dir),
        "translated_markdown": str(translated_path),
        "title": title,
        "wechat_title": wechat_title,
        "digest": digest_from_markdown(markdown),
        "institution_name": institution_name,
        "source_report_name": source_report_name,
        "article": article,
        "cover_image": str(cover_image),
        "inline_images": uploaded_images,
        "content_chars": len(content),
        "content_bytes": utf8_byte_count(content),
        "visible_text_chars": visible_text_chars,
        "body_image_count": body_image_count,
        "ai_image_count": sum(1 for item in uploaded_images if item.get("source") != "mineru"),
    }


def chunked(items: list[Any], size: int) -> list[list[Any]]:
    return [items[idx : idx + size] for idx in range(0, len(items), size)]


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def is_article_size_error(exc: WeChatError) -> bool:
    return exc.errcode == 45008 or "article size out of limit" in str(exc).lower()


def article_payload(items: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [dict(item["article"]) for item in items]


def main() -> int:
    parser = argparse.ArgumentParser(description="Create WeChat Official Account drafts from KC translated reports.")
    parser.add_argument("--translated-root", default="kc_translated_reports")
    parser.add_argument("--date-folder", default="latest")
    parser.add_argument("--output-root", default="wechat_drafts")
    parser.add_argument("--max-articles", default="10")
    parser.add_argument("--article-offset", type=int, default=0)
    parser.add_argument("--articles-per-draft", type=int, default=DEFAULT_ARTICLES_PER_DRAFT)
    parser.add_argument("--max-inline-images", type=int, default=DEFAULT_MIN_INLINE_IMAGES)
    parser.add_argument("--min-inline-images", type=int, default=DEFAULT_MIN_INLINE_IMAGES)
    parser.add_argument("--max-body-chars", type=int, default=DEFAULT_BODY_VISIBLE_CHARS)
    parser.add_argument("--max-content-chars", type=int, default=DEFAULT_MAX_CONTENT_CHARS)
    parser.add_argument("--max-content-bytes", type=int, default=DEFAULT_MAX_CONTENT_BYTES)
    parser.add_argument("--brand", default=BRAND)
    parser.add_argument("--author", default=AUTHOR)
    parser.add_argument("--disclaimer", default=BOTTOM_DISCLAIMER)
    parser.add_argument("--body-hook", default=DEFAULT_BODY_HOOK)
    parser.add_argument("--trailing-image", default=DEFAULT_TRAILING_IMAGE)
    parser.add_argument("--content-source-url", default="")
    parser.add_argument("--wechat-appid", default=os.getenv("WECHAT_MP_APPID", ""))
    parser.add_argument("--wechat-secret", default=os.getenv("WECHAT_MP_APPSECRET", ""))
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--publish", action="store_true", help="Submit each created draft for publishing.")
    parser.add_argument("--dry-run", action="store_true", help="Build payloads without calling WeChat APIs.")
    args = parser.parse_args()

    max_articles = parse_selection_limit(args.max_articles, "--max-articles")
    if args.article_offset < 0:
        raise ValueError("--article-offset must be non-negative")
    if not 1 <= args.articles_per_draft <= 9:
        raise ValueError("--articles-per-draft must be between 1 and 9")
    if args.max_inline_images < 0:
        raise ValueError("--max-inline-images must be non-negative")
    if args.min_inline_images < 0:
        raise ValueError("--min-inline-images must be non-negative")
    if args.max_body_chars < 200:
        raise ValueError("--max-body-chars must be at least 200")
    if not args.dry_run and (not args.wechat_appid or not args.wechat_secret):
        raise ValueError("WECHAT_MP_APPID and WECHAT_MP_APPSECRET are required unless --dry-run is set")

    root = Path(args.translated_root)
    date_dir = latest_date_dir(root) if args.date_folder == "latest" else root / args.date_folder
    if not date_dir.exists():
        raise RuntimeError(f"Date folder not found: {date_dir}")

    report_dirs = find_report_dirs(date_dir)
    if max_articles is None:
        selected = report_dirs[args.article_offset :]
    else:
        selected = report_dirs[args.article_offset : args.article_offset + max_articles]
    if not selected:
        raise RuntimeError(f"No translated reports selected from {date_dir}")

    output_dir = Path(args.output_root) / date_dir.name
    output_dir.mkdir(parents=True, exist_ok=True)
    input_selected_count = len(selected)
    skipped_title_policy: list[dict[str, str]] = []
    allowed_selected: list[Path] = []
    for report_dir in selected:
        metadata = translated_article_title_metadata(report_dir)
        reason = wechat_title_policy_skip_reason(metadata["wechat_title"])
        if reason:
            record = dict(metadata)
            record["skip_reason"] = reason
            skipped_title_policy.append(record)
            log(
                "Skipped WeChat draft article by title policy: "
                f"{metadata['wechat_title']} ({reason})"
            )
        else:
            allowed_selected.append(report_dir)
    selected = allowed_selected

    if not selected:
        summary_path = output_dir / "wechat_draft_summary.json"
        summary = {
            "date_folder": date_dir.name,
            "dry_run": args.dry_run,
            "publish": args.publish,
            "max_articles": "all" if max_articles is None else max_articles,
            "input_selected_count": input_selected_count,
            "selected_count": 0,
            "skipped_title_policy_count": len(skipped_title_policy),
            "skipped_title_policy": skipped_title_policy,
            "draft_count": 0,
            "status": "skipped_title_policy",
            "message": f"All selected translated reports were blocked by WeChat title policy from {date_dir}",
            "drafts": [],
            "articles": [],
        }
        write_json(summary_path, summary)
        log(f"All selected translated reports blocked by title policy; wrote skip summary: {summary_path}")
        return 0

    log(
        f"Selected {len(selected)} translated reports from {date_dir} "
        f"(skipped_title_policy={len(skipped_title_policy)}/{input_selected_count})"
    )

    session: requests.Session | None = None
    access_token: str | None = None
    if not args.dry_run:
        session = requests.Session()
        access_token = get_stable_access_token(session, args.wechat_appid, args.wechat_secret, args.timeout)
        log("Fetched WeChat access token")

    trailing_image_url = ""
    trailing_image_path = resolve_repo_asset_path(args.trailing_image)
    if args.trailing_image and not trailing_image_path:
        raise RuntimeError(f"Trailing image not found: {args.trailing_image}")
    if trailing_image_path:
        if args.dry_run:
            trailing_image_url = fake_static_image_url(str(trailing_image_path))
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            trailing_image_url = upload_article_image(session, access_token, trailing_image_path, args.timeout)
            log(f"Uploaded trailing image: {trailing_image_path}")

    built_articles = [
        build_article(report_dir, idx, args, session, access_token, output_dir, trailing_image_url)
        for idx, report_dir in enumerate(selected, 1)
    ]

    drafts = []

    def create_draft(group: list[dict[str, Any]]) -> None:
        articles = article_payload(group)
        payload_bytes = utf8_byte_count(json.dumps({"articles": articles}, ensure_ascii=False, separators=(",", ":")))
        if args.dry_run:
            media_id = f"DRY_RUN_DRAFT_{len(drafts) + 1:02d}"
            publish_id = f"DRY_RUN_PUBLISH_{len(drafts) + 1:02d}" if args.publish else ""
            reused_existing = False
            draft_get = {
                "ok": True,
                "dry_run": True,
                "article_count": len(articles),
                "expected_article_count": len(articles),
                "matches_expected_article_count": True,
                "titles": [item.get("title", "") for item in articles],
            }
        else:
            if session is None or access_token is None:
                raise RuntimeError("session and access_token are required outside dry-run")
            existing_media_id = find_recent_draft_by_titles(
                session,
                access_token,
                payload_article_titles(articles),
                args.timeout,
            )
            if existing_media_id:
                media_id = existing_media_id
                reused_existing = True
                log(f"Reusing existing WeChat draft with the same article titles: media_id={media_id}")
            else:
                reused_existing = False
                try:
                    media_id = add_draft(session, access_token, articles, args.timeout)
                except WeChatError as exc:
                    if is_article_size_error(exc) and len(group) > 1:
                        split_at = max(1, len(group) // 2)
                        log(
                            "WeChat rejected draft group as too large; "
                            f"splitting {len(group)} articles into {split_at}+{len(group) - split_at} and retrying."
                        )
                        create_draft(group[:split_at])
                        create_draft(group[split_at:])
                        return
                    raise
            draft_get = verify_draft_get(session, access_token, media_id, args.timeout, len(articles))
            publish_id = submit_publish(session, access_token, media_id, args.timeout) if args.publish else ""

        draft_index = len(drafts) + 1
        payload_path = output_dir / f"draft_payload_{draft_index:02d}.json"
        write_json(payload_path, {"articles": articles})
        drafts.append(
            {
                "draft_index": draft_index,
                "media_id": media_id,
                "publish_id": publish_id,
                "published": bool(publish_id),
                "reused_existing": reused_existing,
                "article_count": len(articles),
                "payload_bytes": payload_bytes,
                "payload": str(payload_path),
                "titles": [item["title"] for item in group],
                "wechat_titles": [item["wechat_title"] for item in group],
                "draft_get": draft_get,
            }
        )
        if publish_id:
            log(f"Draft {draft_index}: articles={len(articles)} media_id={media_id} publish_id={publish_id}")
        else:
            log(f"Draft {draft_index}: articles={len(articles)} media_id={media_id}")

    for group in chunked(built_articles, args.articles_per_draft):
        create_draft(group)

    summary = {
        "date_folder": date_dir.name,
        "dry_run": args.dry_run,
        "publish": args.publish,
        "max_articles": "all" if max_articles is None else max_articles,
        "input_selected_count": input_selected_count,
        "selected_count": len(selected),
        "skipped_title_policy_count": len(skipped_title_policy),
        "skipped_title_policy": skipped_title_policy,
        "articles_per_draft": args.articles_per_draft,
        "draft_count": len(drafts),
        "max_body_chars": args.max_body_chars,
        "max_content_chars": args.max_content_chars,
        "max_content_bytes": args.max_content_bytes,
        "min_inline_images": args.min_inline_images,
        "max_inline_images": args.max_inline_images,
        "body_hook": args.body_hook,
        "trailing_image": str(trailing_image_path) if trailing_image_path else "",
        "drafts": drafts,
        "articles": [
            {
                "title": item["title"],
                "wechat_title": item["wechat_title"],
                "institution_name": item["institution_name"],
                "source_report_name": item["source_report_name"],
                "report_dir": item["report_dir"],
                "content_chars": item["content_chars"],
                "content_bytes": item["content_bytes"],
                "visible_text_chars": item["visible_text_chars"],
                "inline_image_count": len(item["inline_images"]),
                "body_image_count": item["body_image_count"],
                "ai_image_count": item["ai_image_count"],
                "cover_image": item["cover_image"],
            }
            for item in built_articles
        ],
    }
    summary_path = output_dir / "wechat_draft_summary.json"
    write_json(summary_path, summary)
    log(f"Wrote summary: {summary_path}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise
